export enum GameMode {
  INTERVALS = 'INTERVALS',
  CHORDS = 'CHORDS',
  MELODY_RECALL = 'MELODY_RECALL',
}

export enum Difficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum InstrumentSoundId {
  SINE = 'SINE',
  SQUARE = 'SQUARE',
  TRIANGLE = 'TRIANGLE',
}

export enum PetId {
  KAKI = 'KAKI',
  PLANIN = 'PLANIN',
  MOOTOD = 'MOOTOD',
  KAKI_EVO1 = 'KAKI_EVO1',
  PLANIN_EVO1 = 'PLANIN_EVO1',
  MOOTOD_EVO1 = 'MOOTOD_EVO1',
}

export enum PetAbilityType {
  GCOIN_DISCOUNT_UNLOCKABLES = 'GCOIN_DISCOUNT_UNLOCKABLES',
  XP_BOOST_TRAINING = 'XP_BOOST_TRAINING',
  PET_XP_BOOST = 'PET_XP_BOOST',
}

export enum AchievementId {
  FIRST_CORRECT_INTERVAL = 'FIRST_CORRECT_INTERVAL',
  FIRST_CORRECT_CHORD = 'FIRST_CORRECT_CHORD',
  FIRST_CORRECT_MELODY = 'FIRST_CORRECT_MELODY',
  REACH_LEVEL_5 = 'REACH_LEVEL_5',
  REACH_LEVEL_10 = 'REACH_LEVEL_10',
  REACH_LEVEL_15 = 'REACH_LEVEL_15',
  STREAK_5 = 'STREAK_5',
  STREAK_10 = 'STREAK_10',
  STREAK_15 = 'STREAK_15',
  MELODY_RECALL_STREAK_3 = 'MELODY_RECALL_STREAK_3',
  MELODY_RECALL_STREAK_7 = 'MELODY_RECALL_STREAK_7',
  COLLECT_100_GCOINS = 'COLLECT_100_GCOINS',
  COLLECT_500_GCOINS = 'COLLECT_500_GCOINS',
  COLLECT_1000_GCOINS = 'COLLECT_1000_GCOINS',
  UNLOCK_FIRST_ADVANCED_ITEM = 'UNLOCK_FIRST_ADVANCED_ITEM',
  PURCHASE_FIRST_SHOP_ITEM = 'PURCHASE_FIRST_SHOP_ITEM',
  ADOPT_FIRST_PET = 'ADOPT_FIRST_PET',
  FEED_PET_FIRST_TIME = 'FEED_PET_FIRST_TIME',
  PET_REACH_LEVEL_5 = 'PET_REACH_LEVEL_5',
  PET_MAX_HAPPINESS = 'PET_MAX_HAPPINESS',
  PET_PLAY_10_TIMES = 'PET_PLAY_10_TIMES',
  PET_COLLECTOR = 'PET_COLLECTOR',
  PET_MAX_LEVEL_FIRST = 'PET_MAX_LEVEL_FIRST',
  PET_CUSTOMIZED_FIRST = 'PET_CUSTOMIZED_FIRST',
  PET_FULFILL_REQUEST_FIRST = 'PET_FULFILL_REQUEST_FIRST',
  FIRST_PET_EVOLUTION = 'FIRST_PET_EVOLUTION',
  M3_NOVICE = 'M3_NOVICE',
  M3_ADEPT = 'M3_ADEPT',
  MAJ_TRIAD_NOVICE = 'MAJ_TRIAD_NOVICE',
  MAJ_TRIAD_ADEPT = 'MAJ_TRIAD_ADEPT',
  MAJ9_INT_NOVICE = 'MAJ9_INT_NOVICE',
  MAJ9_CHORD_NOVICE = 'MAJ9_CHORD_NOVICE',
  ACHIEVE_FIRST_HOUSE = 'ACHIEVE_FIRST_HOUSE',
  ACHIEVE_UPGRADED_HOUSE_LV2 = 'ACHIEVE_UPGRADED_HOUSE_LV2',
  ACHIEVE_UPGRADED_HOUSE_LV3 = 'ACHIEVE_UPGRADED_HOUSE_LV3',
  PURCHASE_FIRST_FURNITURE = 'PURCHASE_FIRST_FURNITURE',
  COMPLETE_FIRST_MISSION = 'COMPLETE_FIRST_MISSION',
  COMPLETE_5_DAILY_MISSIONS = 'COMPLETE_5_DAILY_MISSIONS',
  COMPLETE_FIRST_WEEKLY_MISSION = 'COMPLETE_FIRST_WEEKLY_MISSION',
  DEFEAT_FIRST_MONSTER = 'DEFEAT_FIRST_MONSTER',
  DEFEAT_MONO_NOTE_SLIME = 'DEFEAT_MONO_NOTE_SLIME',
  DEFEAT_CHORD_CRACKER = 'DEFEAT_CHORD_CRACKER',
  DEFEAT_INTERVAL_IMP = 'DEFEAT_INTERVAL_IMP',
  DEFEAT_RHYTHM_LORD = 'DEFEAT_RHYTHM_LORD',
  DEFEAT_HARMONY_SIREN = 'DEFEAT_HARMONY_SIREN',
  COLLECT_ALL_MEMENTOS = 'COLLECT_ALL_MEMENTOS',
  QUEST_ACCEPTED_FIRST = 'QUEST_ACCEPTED_FIRST',
  QUEST_COMPLETED_FIRST = 'QUEST_COMPLETED_FIRST',
  AVATAR_FIRST_CUSTOMIZATION = 'AVATAR_FIRST_CUSTOMIZATION',
  CLOTHING_PURCHASED_FIRST = 'CLOTHING_PURCHASED_FIRST',
  CLOTHING_EQUIPPED_FIRST = 'CLOTHING_EQUIPPED_FIRST',
  FIRST_INTERACTION_MELODIE = 'FIRST_INTERACTION_MELODIE',
  FIRST_GIFT_MELODIE = 'FIRST_GIFT_MELODIE',
  MELODIE_EVENT_1 = 'MELODIE_EVENT_1',
  MELODIE_EVENT_2 = 'MELODIE_EVENT_2',
  MELODIE_EVENT_3 = 'MELODIE_EVENT_3',
  BECOME_LOVERS_MELODIE = 'BECOME_LOVERS_MELODIE',
  MARRIED_MELODIE = 'MARRIED_MELODIE',
  FIRST_INTERACTION_RHYTHM = 'FIRST_INTERACTION_RHYTHM',
  FIRST_GIFT_RHYTHM = 'FIRST_GIFT_RHYTHM',
  RHYTHM_EVENT_1 = 'RHYTHM_EVENT_1',
  RHYTHM_EVENT_2 = 'RHYTHM_EVENT_2',
  RHYTHM_EVENT_3 = 'RHYTHM_EVENT_3',
  BECOME_LOVERS_RHYTHM = 'BECOME_LOVERS_RHYTHM',
  MARRIED_RHYTHM = 'MARRIED_RHYTHM',
  FIRST_INTERACTION_HARMONIE = 'FIRST_INTERACTION_HARMONIE',
  FIRST_GIFT_HARMONIE = 'FIRST_GIFT_HARMONie',
  HARMONIE_EVENT_1 = 'HARMONIE_EVENT_1',
  HARMONIE_EVENT_2 = 'HARMONIE_EVENT_2',
  HARMONIE_EVENT_3 = 'HARMONIE_EVENT_3',
  BECOME_LOVERS_HARMONIE = 'BECOME_LOVERS_HARMONIE',
  MARRIED_HARMONIE = 'MARRIED_HARMONIE',
  HAVE_FIRST_CHILD = 'HAVE_FIRST_CHILD',
  CHILD_FIRST_WORDS = 'CHILD_FIRST_WORDS',
  CHILD_FIRST_STEPS = 'CHILD_FIRST_STEPS',
  DEFEAT_FINAL_BOSS = 'DEFEAT_FINAL_BOSS', // New
}

export enum UnlockedItemType {
  INTERVAL = 'INTERVAL',
  CHORD = 'CHORD',
  INSTRUMENT_SOUND = 'INSTRUMENT_SOUND',
  AVATAR_ITEM = 'AVATAR_ITEM',
  PET_FOOD = 'PET_FOOD',
  PET_CUSTOMIZATION = 'PET_CUSTOMIZATION',
  FURNITURE = 'FURNITURE',
  SONG = 'SONG',
  QUEST_ITEM = 'QUEST_ITEM',
  FACE = 'FACE',
  HAIR_STYLE = 'HAIR_STYLE',
  HAIR_COLOR = 'HAIR_COLOR',
  SKIN_COLOR = 'SKIN_COLOR',
  CLOTHING = 'CLOTHING',
  MEMENTO = 'MEMENTO',
  KEY_ITEM = 'KEY_ITEM',
  GENERAL_GIFT = 'GENERAL_GIFT',
  CHILD_CARE = 'CHILD_CARE',
}

export enum FurnitureId {
  GRAND_PIANO = 'GP_001',
  MUSIC_THEORY_SHELF = 'MTS_001',
  COMFY_PET_BED = 'CPB_001',
}

export enum MissionRewardType {
  GCOINS = 'GCOINS',
  PLAYER_XP = 'PLAYER_XP',
  PET_XP = 'PET_XP',
}

export enum MissionId {
  DAILY_TRAIN_M3_5_TIMES = 'DAILY_TRAIN_M3_5_TIMES',
  DAILY_STREAK_3_CHORDS = 'DAILY_STREAK_3_CHORDS',
  DAILY_FEED_PET_1_TIME = 'DAILY_FEED_PET_1_TIME',
  DAILY_USE_PRACTICE_NOOK_1_TIME = 'DAILY_USE_PRACTICE_NOOK_1_TIME',
  DAILY_EARN_50_GCOINS_TRAINING = 'DAILY_EARN_50_GCOINS_TRAINING',
  WEEKLY_COMPLETE_3_DAILY_MISSIONS = 'WEEKLY_COMPLETE_3_DAILY_MISSIONS',
  WEEKLY_ANSWER_20_INTERVALS_CORRECT = 'WEEKLY_ANSWER_20_INTERVALS_CORRECT',
  WEEKLY_EARN_250_GCOINS_TOTAL = 'WEEKLY_EARN_250_GCOINS_TOTAL',
  DAILY_CHALLENGE_SLIME = 'DAILY_CHALLENGE_SLIME',
  DAILY_PET_MAX_HAPPINESS = 'DAILY_PET_MAX_HAPPINESS',
  DAILY_PLAY_NOTES_FREESTYLE_10 = 'DAILY_PLAY_NOTES_FREESTYLE_10',
  DAILY_TRAIN_MAJ7_CHORD_3_TIMES = 'DAILY_TRAIN_MAJ7_CHORD_3_TIMES',
  WEEKLY_DEFEAT_ANY_2_MONSTERS = 'WEEKLY_DEFEAT_ANY_2_MONSTERS',
  WEEKLY_TRAIN_ADVANCED_INTERVAL_5_TIMES = 'WEEKLY_TRAIN_ADVANCED_INTERVAL_5_TIMES',
}

export enum MissionType {
  TRAIN_ITEM_CORRECT_COUNT = 'TRAIN_ITEM_CORRECT_COUNT',
  TRAINING_STREAK = 'TRAINING_STREAK',
  FEED_PET_COUNT = 'FEED_PET_COUNT',
  USE_PRACTICE_NOOK_COUNT = 'USE_PRACTICE_NOOK_COUNT',
  EARN_GCOINS_FROM_TRAINING = 'EARN_GCOINS_FROM_TRAINING',
  EARN_GCOINS_TOTAL = 'EARN_GCOINS_TOTAL',
  COMPLETE_DAILY_MISSION_COUNT = 'COMPLETE_DAILY_MISSION_COUNT',
  START_MONSTER_BATTLE = 'START_MONSTER_BATTLE',
  DEFEAT_MONSTER_COUNT = 'DEFEAT_MONSTER_COUNT',
  PET_REACH_STAT = 'PET_REACH_STAT',
  PLAY_NOTES_FREESTYLE_COUNT = 'PLAY_NOTES_FREESTYLE_COUNT',
  TRAIN_ADVANCED_ITEM_CORRECT_COUNT = 'TRAIN_ADVANCED_ITEM_CORRECT_COUNT',
}

export enum MonsterId {
  MONO_NOTE_SLIME = 'MONO_NOTE_SLIME',
  CHORD_CRACKER = 'CHORD_CRACKER',
  INTERVAL_IMP = 'INTERVAL_IMP',
  RHYTHM_LORD = 'RHYTHM_LORD',
  HARMONY_SIREN = 'HARMONY_SIREN',
  ECHOING_PHANTOM = 'ECHOING_PHANTOM',
  CHROMATIC_ABERRATION = 'CHROMATIC_ABERRATION',
  CHORDAL_TITAN = 'CHORDAL_TITAN',
  POLYPHONIC_BEHEMOTH = 'POLYPHONIC_BEHEMOTH',
  AURAL_ASCENDANT = 'AURAL_ASCENDANT',
  GRANDMASTER_OF_DIVINE_HEARING = 'GRANDMASTER_OF_DIVINE_HEARING', // New (optional, might not be used as a typical monster)
}

export enum MementoId {
  SLIME_ESSENCE = 'SLIME_ESSENCE',
  CRACKER_TOOTH = 'CRACKER_TOOTH',
  IMP_HORN = 'IMP_HORN',
  RHYTHM_CORE = 'RHYTHM_CORE',
  SIREN_SCALE = 'SIREN_SCALE',
  PHANTOM_ECHO_STONE = 'PHANTOM_ECHO_STONE',
  CHROMATIC_CRYSTAL = 'CHROMATIC_CRYSTAL',
  TITAN_CHORD_FRAGMENT = 'TITAN_CHORD_FRAGMENT',
  BEHEMOTH_VOICEBOX = 'BEHEMOTH_VOICEBOX',
  ASCENDANT_AURA_SHARD = 'ASCENDANT_AURA_SHARD',
}

export enum AvatarStyle {
  TYPE_A = 'TYPE_A',
  TYPE_B = 'TYPE_B',
  TYPE_C = 'TYPE_C',
}

export enum FaceId {
  FACE_1 = 'FACE_1',
  FACE_2 = 'FACE_2',
  FACE_3 = 'FACE_3',
}

export enum HairId {
  HAIR_1 = 'HAIR_1',
  HAIR_2 = 'HAIR_2',
  HAIR_3 = 'HAIR_3',
  HAIR_4 = 'HAIR_4',
  HAIR_5 = 'HAIR_5',
}

export enum HairColorId {
  BLACK = 'BLACK',
  BROWN = 'BROWN',
  BLONDE = 'BLONDE',
  RED = 'RED',
  BLUE = 'BLUE',
}

export enum SkinColorId {
  PALE = 'PALE',
  LIGHT = 'LIGHT',
  TAN = 'TAN',
  MEDIUM = 'MEDIUM',
  DARK = 'DARK',
}

export enum ClothingId {
  BASIC_SHIRT_RED = 'BASIC_SHIRT_RED',
  BASIC_SHIRT_BLUE = 'BASIC_SHIRT_BLUE',
  BASIC_SHIRT_GREEN = 'BASIC_SHIRT_GREEN',
}

export enum ClothingLayer {
  SHIRT = 'SHIRT',
}

export enum NPCId {
  MUSIC_MASTER = 'MUSIC_MASTER',
  MEMENTO_COLLECTOR = 'MEMENTO_COLLECTOR',
  ZALAY_BEAT = 'ZALAY_BEAT',
  MELODIE = 'MELODIE',
  RHYTHM = 'RHYTHM',
  HARMONIE = 'HARMONIE',
}

export enum QuestId {
  LOST_MUSIC_SHEET_MUSIC_MASTER = 'LOST_MUSIC_SHEET_MUSIC_MASTER',
  NEW_PET_TRAINING_MUSIC_MASTER = 'NEW_PET_TRAINING_MUSIC_MASTER',
  INTRO_MELODIE = 'INTRO_MELODIE', 
  INTRO_RHYTHM = 'INTRO_RHYTHM',   
  INTRO_HARMONIE = 'INTRO_HARMONIE', 
  MEMENTO_FOR_COLLECTOR = 'MEMENTO_FOR_COLLECTOR', 
  ZALAY_BEAT_FREESTYLE = 'ZALAY_BEAT_FREESTYLE', 
}

export enum QuestObjectiveType {
  TALK_TO_NPC = 'TALK_TO_NPC',
  COLLECT_ITEM = 'COLLECT_ITEM',
  DEFEAT_MONSTER = 'DEFEAT_MONSTER',
  EXPLORE_AREA = 'EXPLORE_AREA',
  SOLVE_PUZZLE = 'SOLVE_PUZZLE',
  LISTEN_MUSIC = 'LISTEN_MUSIC',
  PLAY_INSTRUMENT = 'PLAY_INSTRUMENT',
  FEED_PET_ITEM = 'FEED_PET_ITEM',
}

export enum SongId {
  ANCIENT_MELODY_SONG = 'ANCIENT_MELODY_SONG',
}

export enum QuestItemId {
  LOST_CLUE = 'LOST_CLUE_ITEM',
  LOST_MUSIC_SHEET = 'LOST_MUSIC_SHEET_ITEM_ID',
  SPECIAL_PET_FOOD = 'SPECIAL_PET_FOOD_ITEM',
  SLIME_ESSENCE_ITEM_ID = 'SLIME_ESSENCE_ITEM_ID',
}

export enum AppView {
  AUDIO_PROMPT = 'AUDIO_PROMPT',
  PLAYER_NAME_INPUT = 'PLAYER_NAME_INPUT',
  MENU = 'MENU',
  DIFFICULTY_SELECTION = 'DIFFICULTY_SELECTION',
  INTERVAL_TRAINER = 'INTERVAL_TRAINER',
  CHORD_TRAINER = 'CHORD_TRAINER',
  MELODY_RECALL_TRAINER = 'MELODY_RECALL_TRAINER',
  SUMMARY_PAGE = 'SUMMARY_PAGE',
  UNLOCKABLES_STORE = 'UNLOCKABLES_STORE',
  SHOP = 'SHOP',
  SETTINGS = 'SETTINGS',
  PET_ADOPTION_PAGE = 'PET_ADOPTION_PAGE',
  PET_MANAGEMENT_PAGE = 'PET_MANAGEMENT_PAGE',
  MY_HOME = 'MY_HOME',
  MISSIONS_PAGE = 'MISSIONS_PAGE',
  MONSTER_LAIR = 'MONSTER_LAIR',
  MONSTER_BATTLE = 'MONSTER_BATTLE',
  MONSTERPEDIA = 'MONSTERPEDIA',
  FREESTYLE_JAM_ROOM = 'FREESTYLE_JAM_ROOM',
  GAME_GUIDE_PAGE = 'GAME_GUIDE_PAGE',
  AVATAR_CUSTOMIZATION = 'AVATAR_CUSTOMIZATION',
  NPC_HUB = 'NPC_HUB',
  QUEST_INTERACTION = 'QUEST_INTERACTION',
  QUEST_LOG = 'QUEST_LOG',
  NPC_INTERACTION_MELODIE = 'NPC_INTERACTION_MELODIE',
  NPC_INTERACTION_RHYTHM = 'NPC_INTERACTION_RHYTHM',
  NPC_INTERACTION_HARMONIE = 'NPC_INTERACTION_HARMONIE',
  RELATIONSHIP_JOURNAL = 'RELATIONSHIP_JOURNAL',
  GIFTING_PAGE = 'GIFTING_PAGE',
  CHILD_NAMING_PAGE = 'CHILD_NAMING_PAGE',
  FINAL_BOSS_BATTLE = 'FINAL_BOSS_BATTLE', // New
}

export enum ShopItemId {
  HEART_NOTE_LOCKET = 'HEART_NOTE_LOCKET',
  WEDDING_RING = 'WEDDING_RING',
  FLOWER_BOUQUET = 'FLOWER_BOUQUET',
  CHOCOLATE_BOX = 'CHOCOLATE_BOX',
  SPICY_SNACKS = 'SPICY_SNACKS',
  OLD_BOOK = 'OLD_BOOK',
  TEA_SET = 'TEA_SET',
  HANDMADE_COOKIE = 'HANDMADE_COOKIE',
  BABY_CRIB = 'BABY_CRIB',
  MILK_POWDER = 'MILK_POWDER',
  BABY_FOOD = 'BABY_FOOD',
  DIAPERS = 'DIAPERS',
  CHILD_CARE_KIT = 'CHILD_CARE_KIT',
  BIRTHDAY_CAKE = 'BIRTHDAY_CAKE', 
}

export enum PetCustomizationItemId {
  COLLAR_RED = 'COLLAR_RED',
  COLLAR_BLUE = 'COLLAR_BLUE',
  COLLAR_GREEN = 'COLLAR_GREEN',
}

export enum RelationshipStatus {
  NEUTRAL = 'NEUTRAL',
  FRIENDLY = 'FRIENDLY',
  DATING = 'DATING',
  MARRIED = 'MARRIED',
}

export enum GiftPreferenceLevel {
  LOVED = 'LOVED',
  LIKED = 'LIKED',
  NEUTRAL = 'NEUTRAL',
  DISLIKED = 'DISLIKED',
}

export enum QuestStatusEnum { 
  UNAVAILABLE = 'unavailable',
  AVAILABLE = 'available',
  ACTIVE = 'active',
  COMPLETED = 'completed',
  CLAIMED = 'claimed',
}

export enum ChildGrowthStage {
  INFANT = 'INFANT',
  CRAWLER = 'CRAWLER',
  TODDLER = 'TODDLER',
  SCHOOL_AGE = 'SCHOOL_AGE',
}

export enum ChildNeedType {
  HUNGER = 'HUNGER',
  CLEANLINESS = 'CLEANLINESS',
  AFFECTION = 'AFFECTION',
  SLEEP = 'SLEEP',
  SICKNESS = 'SICKNESS',
}

export enum ChildEvent {
  FIRST_WORDS = 0,
  FIRST_STEPS = 1,
  STARTED_SCHOOL = 2,
}

export enum FamilyActivityId {
  PARK_TRIP = 'PARK_TRIP',
  BIRTHDAY_CELEBRATION = 'BIRTHDAY_CELEBRATION', 
}