
import { ThaiUIText } from './types';
import { PET_DEFINITIONS, MAX_PET_LEVEL } from './pet-constants';

export const UI_TEXT_TH: ThaiUIText = {
  appName: "เกมฝึกทักษะการฟัง",
  intervalTraining: "ฝึกจำขั้นคู่เสียง",
  chordTraining: "ฝึกจำคอร์ด",
  melodyRecallTraining: "ฝึกทักษะจำทำนอง",
  melodyRecallTrainingButton: "ห้องฝึกเพลงตามสั่ง",
  playPrompt: "กดปุ่มรูปลำโพงเพื่อฟังเสียง",
  selectAnswer: "เลือกคำตอบที่ถูกต้อง:",
  correct: "ถูกต้อง!",
  incorrect: "ผิด!",
  nextQuestion: "คำถามถัดไป",
  score: "คะแนน:",
  chooseMode: "เลือกโหมดการเล่น:",
  backToMenu: "กลับเมนูหลัก",
  replaySound: "ฟังอีกครั้ง",
  yourAnswer: "คำตอบของคุณ:",
  correctAnswerIs: "คำตอบที่ถูกต้องคือ:",
  level: "ระดับ:",
  start: "เริ่มเกม",
  loading: "กำลังโหลด...",
  difficulty: "ระดับความยาก",
  difficultyPrompt: "เลือกระดับความยาก:",
  easy: "ง่าย (3 โน้ต)",
  medium: "ปานกลาง (4 โน้ต)",
  hard: "ยาก (5 โน้ต)",
  audioContextPrompt: "เกมนี้ต้องใช้เสียง โปรดกดปุ่ม \"เริ่มเกม\" เพื่อเปิดใช้งานเสียง",
  audioNotSupported: "เบราว์เซอร์ของคุณไม่รองรับ Web Audio API ที่จำเป็นสำหรับเกมนี้",
  loadingAudio: "กำลังเตรียมระบบเสียง...",
  currentStreak: "สถิติทำถูกติดต่อกัน:",
  highScore: "คะแนนสูงสุด:",
  submitAnswer: "ส่งคำตอบ",
  clearInput: "ล้าง",
  notesPlayedPrompt: "กดโน้ตบนเปียโนตามทำนองที่ได้ยิน:",
  notesYouPlayed: "โน้ตที่คุณเล่น:",


  playerLevel: "เลเวล",
  xp: "XP",
  gCoins: "G-Coins",
  achievements: "ความสำเร็จ",
  achievementUnlocked: "ปลดล็อกความสำเร็จ!",
  levelUp: "เลเวลอัพ!",

  summaryPageTitle: "สรุปผลและความก้าวหน้า",
  playerStats: "สถิติผู้เล่น",
  unlockedAchievements: "ความสำเร็จที่ปลดล็อกแล้ว",
  masteryProgress: "ความคืบหน้าการฝึกฝน",
  intervalsMastery: "ความเชี่ยวชาญขั้นคู่เสียง",
  chordsMastery: "ความเชี่ยวชาญคอร์ด",
  melodyRecallMastery: "ความเชี่ยวชาญการจำทำนอง",
  correctAnswersLabel: "ตอบถูก:",
  nextMilestoneLabel: "เป้าหมายถัดไป:",
  forAchievementText: "สำหรับ",
  allMasteryAchievementsUnlocked: "ปลดล็อกความสำเร็จทั้งหมดสำหรับรายการนี้แล้ว",
  viewSummary: "ดูสรุปผล",
  noAchievementsUnlocked: "ยังไม่มีความสำเร็จที่ปลดล็อก",
  totalCorrectAnswers: "จำนวนครั้งที่ตอบถูกทั้งหมด",

  unlockablesStoreTitle: "ปลดล็อกเนื้อหาดนตรี",
  unlockItem: "ปลดล็อก",
  unlocked: "ปลดล็อกแล้ว",
  costLabel: "ราคา:",
  notEnoughGCoins: "G-Coins ไม่เพียงพอ!",
  dailyRewardTitle: "รางวัลล็อกอินรายวัน!",
  dailyRewardMessage: "คุณได้รับ {amount} G-Coins สำหรับการล็อกอินวันนี้!",
  dailyRewardHouseBonusMessage: "คุณได้รับ {amount} G-Coins (รวมโบนัสจากบ้าน {bonusAmount}!) สำหรับการล็อกอินวันนี้!",

  shopTitle: "ร้านค้าไอเทม",
  shopDescription: "ใช้ G-Coins ของคุณเพื่อซื้อไอเทมเสริมต่างๆ!",
  purchaseItem: "ซื้อ",
  purchased: "ซื้อแล้ว",
  settingsTitle: "ตั้งค่าเกม",
  selectInstrumentSound: "เลือกเสียงเครื่องดนตรี:",
  currentSoundLabel: "เสียงปัจจุบัน:",
  instrumentSoundSine: "เสียง Sine Wave (เริ่มต้น)",
  instrumentSoundSquare: "เสียง Square Wave",
  instrumentSoundTriangle: "เสียง Triangle Wave",
  itemPurchasedSuccess: "คุณซื้อ {itemName} สำเร็จ!",
  viewShop: "ร้านค้า",
  viewUnlockables: "ปลดล็อกเนื้อหา",
  viewSettings: "ตั้งค่า",
  settingHighlightPianoOnPlayLabel: "ไฮไลท์เปียโนเมื่อเล่นโจทย์",
  settingHighlightPianoOnPlayDesc: "เมื่อเปิดใช้งาน ลิ่มเปียโนที่เกี่ยวข้องกับโจทย์จะถูกไฮไลท์ขณะเล่นเสียง",
  avatarCustomizationTitle: "ปรับแต่งกรอบอวตาร",
  avatarStyleLabel: "เลือกสไตล์กรอบอวตาร:",
  avatarStyleTypeA: "เริ่มต้น (วงกลม)",
  avatarStyleTypeB: "ไอคอน (สี่เหลี่ยม)",
  avatarStyleTypeC: "สี่เหลี่ยม",
  appearanceCustomizationTitle: "ปรับแต่งรูปลักษณ์",
  faceLabel: "ใบหน้า:",
  hairStyleLabel: "ทรงผม:",
  hairColorLabel: "สีผม:",
  skinColorLabel: "สีผิว:",
  face_FACE_1_name: "ใบหน้าแบบ 1", face_FACE_2_name: "ใบหน้าแบบ 2", face_FACE_3_name: "ใบหน้าแบบ 3",
  hair_HAIR_1_name: "ทรงผมแบบ 1", hair_HAIR_2_name: "ทรงผมแบบ 2", hair_HAIR_3_name: "ทรงผมแบบ 3", hair_HAIR_4_name: "ทรงผมแบบ 4", hair_HAIR_5_name: "ทรงผมแบบ 5",
  color_BLACK_name: "สีดำ", color_BROWN_name: "สีน้ำตาล", color_BLONDE_name: "สีบลอนด์", color_RED_name: "สีแดง", color_BLUE_name: "สีน้ำเงิน",
  color_LIGHT_name: "สีอ่อน", color_MEDIUM_name: "สีปานกลาง", color_DARK_name: "สีเข้ม", color_PALE_name: "สีซีด", color_TAN_name: "สีแทน",
  saveAppearanceButton: "บันทึกรูปลักษณ์",
  avatarAppearanceUpdated: "อัปเดตลักษณะตัวละครแล้ว!",
  clothingSectionTitle: "เสื้อผ้า",
  clothing_BASIC_SHIRT_RED_name: "เสื้อเชิ้ตสีแดง", clothing_BASIC_SHIRT_RED_desc: "เสื้อเชิ้ตสีแดงเรียบๆ ดูดีมีสไตล์",
  clothing_BASIC_SHIRT_BLUE_name: "เสื้อเชิ้ตสีน้ำเงิน", clothing_BASIC_SHIRT_BLUE_desc: "เสื้อเชิ้ตสีน้ำเงินสุดเท่",
  clothing_BASIC_SHIRT_GREEN_name: "เสื้อเชิ้ตสีเขียว", clothing_BASIC_SHIRT_GREEN_desc: "เสื้อเชิ้ตสีเขียวสบายตา",
  equipClothingButton: "สวมใส่",
  unequipClothingButton: "ถอดออก",
  clothingEquippedMessage: "สวมใส่ {itemName} แล้ว",
  clothingUnequippedMessage: "ถอด {itemName} แล้ว",
  petAdoptionCenterTitle: "ศูนย์รับเลี้ยงเพื่อนซี้",
  adoptPetButton: "รับเลี้ยง {petName}",
  petNameLabel: "ชื่อเพื่อนซี้:",
  petHungerLabel: "ความหิว:",
  feedPetButton: "ให้อาหาร",
  petFoodName: "อาหารเพื่อนซี้ (Buddy Bites)",
  petFoodDescription: "อาหารอร่อยสำหรับเพื่อนซี้ของคุณ",
  notEnoughPetFood: "อาหารเพื่อนซี้ไม่เพียงพอ",
  petAdoptedSuccess: "คุณได้รับเลี้ยง {petName} แล้ว!",
  petFedSuccess: "คุณให้อาหาร {petName} แล้ว!",

  petKakiName: "คากิ",
  petPlaninName: "ปลานิล",
  petMootodName: "หมูทอด",
  petHoodeeName: "น้องหูดี (เก่า)",
  petRhythmoName: "น้องจังหวะ (เก่า)",
  petMelodiaName: "น้องทำนอง (เก่า)",
  petKakiEvo1Name: "คากิ ร่างสุดยอด",
  petPlaninEvo1Name: "ปลานิล ร่างสุดยอด",
  petMootodEvo1Name: "หมูทอด ร่างสุดยอด",

  viewPetAdoption: "ศูนย์เพื่อนซี้",
  manageMyPet: "จัดการเพื่อนซี้",
  manageMyPetTooltipNoPets: "คุณยังไม่มีเพื่อนซี้ ไปรับเลี้ยงก่อนนะ!",
  petStatusTitle: "เพื่อนซี้ของฉัน",
  petHungryNotificationTitle: "เพื่อนซี้หิวแล้ว!",
  petHungryNotificationMessage: "{petName} ดูหิวๆ นะ ให้อาหารหน่อยเร็ว!",
  petAlreadyOwned: "คุณมีเพื่อนซี้ตัวนี้แล้ว",

  petLevelLabel: "เลเวลเพื่อนซี้:",
  petXpLabel: "XP เพื่อนซี้:",
  petHappinessLabel: "ความสุข:",
  playWithPetButton: "เล่นด้วย",
  petPlayCooldownMessage: "คุณเพิ่งเล่นกับเพื่อนซี้ไปเมื่อไม่นานนี้ ลองอีกครั้งในภายหลังนะ",
  petLevelUpNotificationTitle: "เพื่อนซี้เลเวลอัพ!",
  petLevelUpNotificationMessage: "{petName} เลเวลอัพเป็น {level} แล้วนะ!",
  petMaxHappinessMessage: "{petName} ดูมีความสุขสุดๆ ไปเลย!",
  petEvolutionTitle: "พัฒนาร่างสำเร็จ!",
  petEvolutionMessage: "{petName} พัฒนาร่างเป็น {evolvedPetName} แล้ว! เท่สุดๆไปเลย!",

  petManagementTitle: "จัดการเพื่อนซี้",
  selectActivePetLabel: "เลือกเพื่อนซี้ตัวโปรด:",
  activePetLabel: "เพื่อนซี้ปัจจุบัน:",
  ownedPetsLabel: "เพื่อนซี้ของคุณ:",
  noOwnedPets: "คุณยังไม่มีเพื่อนซี้เลย ไปรับเลี้ยงได้ที่ศูนย์ฯ",
  customizePetLabel: "แต่งตัวเพื่อนซี้:",
  applyCustomizationButton: "ใช้",
  petCustomizationColorRed: "ปลอกคอสีแดง",
  petCustomizationColorBlue: "ปลอกคอสีฟ้า",
  petCustomizationColorGreen: "ปลอกคอสีเขียว",
  petCustomizationApplied: "แต่งตัวให้ {petName} ด้วย {itemName} แล้ว!",
  petAbilityLabel: "ความสามารถ:",
  petAbilityDesc_GCOIN_DISCOUNT_UNLOCKABLES: "ลดราคาปลดล็อกเนื้อหาดนตรี {value}%",
  petAbilityDesc_XP_BOOST_TRAINING: "เพิ่ม XP จากการฝึกฝน {value}%",
  petAbilityDesc_PET_XP_BOOST: "เพื่อนซี้ได้รับ XP เพิ่มขึ้น {value}%",
  noActivePetAbility: "ไม่มีความสามารถพิเศษ",
  petSpecialRequestTitle: "คำขอจากเพื่อนซี้!",
  petSpecialRequestListenTo: "{petName} อยากฟังเสียง {targetName} จังเลย! ช่วยหน่อยได้ไหม?",
  petSpecialRequestFulfilled: "เย้! {petName} ดีใจมากเลยที่คุณทำตามคำขอ!",
  petSpecialRequestExpiredMessage: "คำขอของ {petName} หมดอายุแล้ว ดูเหมือน {petName} จะเสียใจนะ...",
  petAbilityDisabledLowHappinessMessage: "ความสามารถของ {petName} ไม่ทำงานเนื่องจากความสุขต่ำเกินไป",


  petKakiDescription: "คากิ ผู้รักการฟังเสียงทุกชนิด ชอบเรียนรู้ไปพร้อมกับคุณ",
  petPlaninDescription: "ปลานิล ชอบดนตรีที่มีชีวิตชีวาและสนุกกับการปลดล็อกสิ่งใหม่ๆ",
  petMootodDescription: "หมูทอด หลงใหลในท่วงทำนองอันไพเราะ และช่วยให้คุณเก่งขึ้น",
  petHoodeeDescription: "น้องหูดี ผู้รักการฟังเสียงทุกชนิด (เก่า)",
  petRhythmoDescription: "น้องจังหวะ ชอบดนตรีที่มีชีวิตชีวา (เก่า)",
  petMelodiaDescription: "น้องทำนอง หลงใหลในท่วงทำนอง (เก่า)",
  petKakiEvo1Description: "คากิในร่างพัฒนา พร้อมพลังแห่งเสียงที่เฉียบคมยิ่งขึ้น!",
  petPlaninEvo1Description: "ปลานิลในร่างพัฒนา คล่องแคล่วและเชี่ยวชาญด้านเศรษฐศาสตร์ดนตรี!",
  petMootodEvo1Description: "หมูทอดในร่างพัฒนา เต็มเปี่ยมด้วยแรงบันดาลใจจากท่วงทำนอง!",

  playerNameInputTitle: "ตั้งชื่อผู้เล่น",
  enterPlayerNamePrompt: "กรุณาตั้งชื่อผู้เล่นของคุณ:",
  submitPlayerNameButton: "ยืนยันชื่อ",
  playerNameDisplayLabel: "ผู้เล่น:",

  saveGameButton: "บันทึกเกม",
  saveGameSuccessMessage: "บันทึกเกมสำเร็จ!",
  resetGameButton: "เริ่มเกมใหม่",
  confirmResetMessage: "คุณแน่ใจหรือไม่ว่าต้องการเริ่มเกมใหม่? ข้อมูลทั้งหมดจะถูกลบ",
  gameResetSuccessMessage: "รีเซ็ตเกมสำเร็จ! กำลังเริ่มเกมใหม่...",

  myHomeScreenTitle: "บ้านของฉัน",
  currentHouseLevelLabel: "ระดับบ้านปัจจุบัน:",
  upgradeHouseButton: "อัปเกรดบ้าน",
  upgradeToLevelLabel: "อัปเกรดเป็น Level {level}",
  notEnoughGCoinsForUpgrade: "G-Coins ของคุณไม่เพียงพอสำหรับการอัปเกรดนี้",
  houseUpgradeSuccess: "อัปเกรดบ้านเป็น Level {level} สำเร็จ!",
  maxHouseLevelReached: "บ้านของคุณถึงระดับสูงสุดแล้ว!",
  houseLevel0Name: "ที่ดินเปล่า",
  houseLevel1Name: "กระท่อมไม้",
  houseLevel2Name: "บ้านไม้สองชั้น",
  houseLevel3Name: "คฤหาสน์หลังเล็ก",
  houseBenefitDescription: "สิทธิประโยชน์ปัจจุบันจากบ้าน:",
  houseBenefitDailyBonus: "+{amount} G-Coins จากรางวัลล็อกอินรายวัน",
  houseBenefitXpBonus: "+{percent}% XP จากการฝึกฝน",
  houseBenefitGCoinBonus: "+{percent}% G-Coins จากการฝึกฝน",
  newHouseBenefitsUnlocked: "ปลดล็อกสิทธิประโยชน์ใหม่จากบ้าน!",
  isInTheHouse: "อยู่ในบ้าน",
  furnitureShopSectionTitle: "ร้านค้าเฟอร์นิเจอร์",
  myFurnitureAndEffectsTitle: "เฟอร์นิเจอร์และโบนัส",
  noFurnitureOwned: "คุณยังไม่มีเฟอร์นิเจอร์เลย ลองไปซื้อที่ร้านค้าดูสิ!",

  furniture_GP_001_name: "แกรนด์เปียโน",
  furniture_GP_001_desc: "เปียโนหลังงามที่ช่วยให้การฝึกฝนมีประสิทธิภาพยิ่งขึ้น",
  furniture_GP_001_effectDesc: "+2% XP จากการฝึกฝน",
  furniture_MTS_001_name: "ชั้นหนังสือทฤษฎีดนตรี",
  furniture_MTS_001_desc: "ชั้นหนังสือที่เต็มไปด้วยความรู้ทางดนตรี ช่วยให้คุณเข้าใจเนื้อหาลึกซึ้งได้ง่ายขึ้น",
  furniture_MTS_001_effectDesc: "ส่วนลด 3% สำหรับการปลดล็อกเนื้อหาดนตรีขั้นสูง",
  furniture_CPB_001_name: "เตียงนอนนุ่มนิ่มสำหรับเพื่อนซี้",
  furniture_CPB_001_desc: "เตียงนอนแสนสบายที่ทำให้เพื่อนซี้ของคุณผ่อนคลายและมีความสุขมากขึ้น",
  furniture_CPB_001_effectDesc: "+5 ความสุขเพิ่มเติม เมื่อให้อาหารหรือเล่นกับเพื่อนซี้",

  practiceNookTitle: "มุมซ้อมดนตรี",
  practiceNookDescription: "ใช้เวลาซ้อมดนตรีส่วนตัวเพื่อเพิ่ม XP และความสุขให้เพื่อนซี้เล็กน้อย",
  practiceNookButtonText: "เริ่มซ้อมดนตรี",
  practiceNookCooldownMessage: "คุณเพิ่งซ้อมไป กลับมาใหม่ในอีก {time}",
  practiceNookRewardMessage: "การซ้อมสำเร็จ! ได้รับ Player XP: {playerXp}, {petName} ได้รับ Pet XP: {petXp} และความสุข +{petHappiness}!",
  practiceNookPetNotActiveMessage: "การซ้อมสำเร็จ! ได้รับ Player XP: {playerXp} (ไม่มีเพื่อนซี้ร่วมซ้อม)",
  missionsPageTitle: "ภารกิจ",
  dailyMissionsTitle: "ภารกิจประจำวัน",
  weeklyMissionsTitle: "ภารกิจประจำสัปดาห์",
  claimRewardButton: "รับรางวัล",
  rewardClaimedButton: "รับรางวัลแล้ว",
  missionProgressLabel: "ความคืบหน้า:",
  missionRewardsLabel: "รางวัล:",
  missionCompletedNotificationTitle: "สำเร็จภารกิจ!",
  missionRewardClaimedNotificationTitle: "รับรางวัลภารกิจแล้ว!",
  noActiveMissions: "ไม่มีภารกิจที่ใช้งานอยู่ในขณะนี้",
  mission_DAILY_TRAIN_M3_5_TIMES_desc: "ฝึกขั้นคู่ Major Third (M3) ให้ถูกต้อง 5 ครั้ง",
  mission_DAILY_STREAK_3_CHORDS_desc: "ทำสถิติตอบถูกติดต่อกัน 3 ครั้งในโหมดฝึกคอร์ด",
  mission_DAILY_FEED_PET_1_TIME_desc: "ให้อาหารเพื่อนซี้ 1 ครั้ง",
  mission_DAILY_USE_PRACTICE_NOOK_1_TIME_desc: "ใช้มุมซ้อมดนตรี 1 ครั้ง",
  mission_DAILY_EARN_50_GCOINS_TRAINING_desc: "รับ 50 G-Coins จากการฝึกฝน",
  mission_WEEKLY_COMPLETE_3_DAILY_MISSIONS_desc: "ทำภารกิจประจำวันสำเร็จ 3 ภารกิจ",
  mission_WEEKLY_ANSWER_20_INTERVALS_CORRECT_desc: "ตอบคำถามขั้นคู่เสียงถูก 20 ครั้ง",
  mission_WEEKLY_EARN_250_GCOINS_TOTAL_desc: "รับ G-Coins ทั้งหมด 250 เหรียญ",
  mission_DAILY_CHALLENGE_SLIME_desc: "ท้าทาย Mono Note Slime 1 ครั้ง",
  mission_DAILY_PET_MAX_HAPPINESS_desc: "ทำให้ความสุขของเพื่อนซี้เต็ม 100",
  mission_DAILY_PLAY_NOTES_FREESTYLE_10_desc: "เล่นโน้ตในห้อง Freestyle Jam 10 ตัว",
  mission_DAILY_TRAIN_MAJ7_CHORD_3_TIMES_desc: "ฝึกคอร์ด Major 7th (maj7) ให้ถูกต้อง 3 ครั้ง",
  mission_WEEKLY_DEFEAT_ANY_2_MONSTERS_desc: "ปราบอสูรใดก็ได้ 2 ตัว",
  mission_WEEKLY_TRAIN_ADVANCED_INTERVAL_5_TIMES_desc: "ฝึกขั้นคู่เสียงขั้นสูงให้ถูกต้อง 5 ครั้ง",
  monsterLairTitle: "ถ้ำอสูรดนตรี",
  monsterBattleTitle: "ท้าประลองอสูร",
  monsterpediaTitle: "สารานุกรมอสูร",
  challengeMonsterButton: "ท้าทาย!",
  monsterDefeatedStatus: "พิชิตแล้ว",
  monsterNotDefeatedStatus: "ยังไม่ได้พิชิต",
  monsterBattleStageLabel: "ด่านที่ {current} / {total}",
  monsterBattleGoodLuckMessage: "ขอให้โชคดีกับการต่อสู้!",
  monsterBattleDefeatMessage: "คุณพ่ายแพ้...",
  monsterBattleVictoryMessage: "ยินดีด้วย! คุณชนะ!",
  monsterBattleRewardMessage: "คุณได้รับ {mementoName} และ {gcoins} G-Coins!",
  viewMonsterpedia: "ดูสารานุกรมอสูร",
  noMementosCollected: "ยังไม่ได้เก็บของที่ระลึกจากอสูรเลย",
  monster_MONO_NOTE_SLIME_name: "โมโนโน้ตสไลม์",
  monster_MONO_NOTE_SLIME_desc: "สไลม์ที่ชอบเสียงโน้ตเดี่ยวๆ",
  monster_CHORD_CRACKER_name: "คอร์ดแครกเกอร์",
  monster_CHORD_CRACKER_desc: "อสูรผู้ชื่นชอบการทำลายคอร์ดที่ไม่ถูกต้อง",
  monster_INTERVAL_IMP_name: "อินเทอร์วัลอิมพ์",
  monster_INTERVAL_IMP_desc: "ภูตตัวน้อยที่ชอบเล่นกับขั้นคู่เสียง",
  monster_RHYTHM_LORD_name: "เจ้าแห่งจังหวะ",
  monster_RHYTHM_LORD_desc: "อสูรทรงพลังผู้ควบคุมจังหวะและทำนอง",
  monster_HARMONY_SIREN_name: "ไซเรนแห่งฮาร์โมนี",
  monster_HARMONY_SIREN_desc: "อสูรเสียงใสผู้หลงใหลในความกลมกลืน",
  monster_ECHOING_PHANTOM_name: "ภูตเสียงสะท้อน",
  monster_ECHOING_PHANTOM_desc: "ภูตลึกลับที่ชอบเล่นกับเสียงสะท้อน ทดสอบความแม่นยำในการฟังเสียงที่คล้ายคลึงกัน",
  monster_CHROMATIC_ABERRATION_name: "อสูรสีเพี้ยน",
  monster_CHROMATIC_ABERRATION_desc: "อสูรที่ชอบความซับซ้อนของเสียงที่ใกล้เคียงกัน",
  monster_CHORDAL_TITAN_name: "ไททันแห่งคอร์ด",
  monster_CHORDAL_TITAN_desc: "อสูรยักษ์ใหญ่ที่ทดสอบความเข้าใจในโครงสร้างคอร์ดและขั้นคู่ที่กว้าง",
  monster_POLYPHONIC_BEHEMOTH_name: "อสูรหลายสำเนียง",
  monster_POLYPHONIC_BEHEMOTH_desc: "อสูรที่สามารถสร้างเสียงที่ซับซ้อนหลายชั้น",
  monster_AURAL_ASCENDANT_name: "อสูรโสตทิพย์",
  monster_AURAL_ASCENDANT_desc: "อสูรระดับสูงที่ทดสอบความสามารถในการฟังเสียงที่เฉียบคมที่สุด",
  memento_SLIME_ESSENCE_name: "แก่นสไลม์",
  memento_SLIME_ESSENCE_desc: "หยดแก่นใสจากโมโนโน้ตสไลม์",
  memento_CRACKER_TOOTH_name: "ฟันแครกเกอร์",
  memento_CRACKER_TOOTH_desc: "เศษฟันแหลมคมของคอร์ดแครกเกอร์",
  memento_IMP_HORN_name: "เขาอิมพ์",
  memento_IMP_HORN_desc: "เขาเล็กๆ ของอินเทอร์วัลอิมพ์",
  memento_RHYTHM_CORE_name: "แกนจังหวะ",
  memento_RHYTHM_CORE_desc: "แกนพลังงานที่สั่นสะเทือนด้วยจังหวะจากเจ้าแห่งจังหวะ",
  memento_SIREN_SCALE_name: "เกล็ดไซเรน",
  memento_SIREN_SCALE_desc: "เกล็ดเงางามจากไซเรนแห่งฮาร์โมนี",
  memento_PHANTOM_ECHO_STONE_name: "ศิลาเสียงสะท้อน",
  memento_PHANTOM_ECHO_STONE_desc: "ศิลาที่กักเก็บเสียงสะท้อนอันแผ่วเบา",
  memento_CHROMATIC_CRYSTAL_name: "ผลึกสีรุ้ง",
  memento_CHROMATIC_CRYSTAL_desc: "ผลึกที่ส่องประกายสีสันหลากหลายเมื่อต้องแสง",
  memento_TITAN_CHORD_FRAGMENT_name: "สะเก็ดคอร์ดไททัน",
  memento_TITAN_CHORD_FRAGMENT_desc: "ชิ้นส่วนของคอร์ดโบราณที่ทรงพลัง",
  memento_BEHEMOTH_VOICEBOX_name: "กล่องเสียงอสูร",
  memento_BEHEMOTH_VOICEBOX_desc: "กล่องเสียงที่สามารถเปล่งได้หลากหลายสำเนียง",
  memento_ASCENDANT_AURA_SHARD_name: "เศษเสี้ยวออร่าทิพย์",
  memento_ASCENDANT_AURA_SHARD_desc: "เศษเสี้ยวพลังงานที่ส่องแสงแห่งความรู้ทางโสตประสาท",
  ach_ACHIEVE_FIRST_HOUSE_name: "บ้านหลังแรก",
  ach_ACHIEVE_FIRST_HOUSE_desc: "สร้างบ้านหลังแรกของคุณสำเร็จ",
  ach_ACHIEVE_UPGRADED_HOUSE_LV2_name: "บ้านใหญ่ขึ้นอีกนิด",
  ach_ACHIEVE_UPGRADED_HOUSE_LV2_desc: "อัปเกรดบ้านเป็นระดับ 2",
  ach_ACHIEVE_UPGRADED_HOUSE_LV3_name: "คฤหาสน์น้อยน่าอยู่",
  ach_ACHIEVE_UPGRADED_HOUSE_LV3_desc: "อัปเกรดบ้านเป็นระดับ 3",
  ach_PURCHASE_FIRST_FURNITURE_name: "นักตกแต่งมือใหม่",
  ach_PURCHASE_FIRST_FURNITURE_desc: "ซื้อเฟอร์นิเจอร์ชิ้นแรก",
  ach_AVATAR_FIRST_CUSTOMIZATION_name: "สไตล์ลิสต์ฝึกหัด",
  ach_AVATAR_FIRST_CUSTOMIZATION_desc: "ปรับแต่งตัวละครของคุณครั้งแรก",
  ach_CLOTHING_PURCHASED_FIRST_name: "แฟชั่นนิสต้า",
  ach_CLOTHING_PURCHASED_FIRST_desc: "ซื้อเสื้อผ้าชิ้นแรก",
  ach_CLOTHING_EQUIPPED_FIRST_name: "ชุดใหม่ไฉไลกว่าเดิม",
  ach_CLOTHING_EQUIPPED_FIRST_desc: "สวมใส่เสื้อผ้าชิ้นแรก",
  ach_FIRST_INTERACTION_MELODIE_name: "พบเมโลดี้",
  ach_FIRST_INTERACTION_MELODIE_desc: "พูดคุยกับเมโลดี้เป็นครั้งแรก",
  ach_FIRST_GIFT_MELODIE_name: "ของขวัญให้เมโลดี้",
  ach_FIRST_GIFT_MELODIE_desc: "มอบของขวัญให้เมโลดี้เป็นครั้งแรก",
  ach_FIRST_INTERACTION_RHYTHM_name: "พบริทึ่ม",
  ach_FIRST_INTERACTION_RHYTHM_desc: "พูดคุยกับริทึ่มเป็นครั้งแรก",
  ach_FIRST_GIFT_RHYTHM_name: "ของขวัญให้ริทึ่ม",
  ach_FIRST_GIFT_RHYTHM_desc: "มอบของขวัญให้ริทึ่มเป็นครั้งแรก",
  ach_FIRST_INTERACTION_HARMONIE_name: "พบฮาร์โมนี่",
  ach_FIRST_INTERACTION_HARMONIE_desc: "พูดคุยกับฮาร์โมนี่เป็นครั้งแรก",
  ach_FIRST_GIFT_HARMONIE_name: "ของขวัญให้ฮาร์โมนี่",
  ach_FIRST_GIFT_HARMONIE_desc: "มอบของขวัญให้ฮาร์โมนี่เป็นครั้งแรก",
  ach_MELODIE_EVENT_1_name: "ความทรงจำของเมโลดี้ 1",
  ach_MELODIE_EVENT_1_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์แรกกับเมโลดี้",
  ach_MELODIE_EVENT_2_name: "ความทรงจำของเมโลดี้ 2",
  ach_MELODIE_EVENT_2_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์ที่สองกับเมโลดี้",
  ach_MELODIE_EVENT_3_name: "ความทรงจำของเมโลดี้ 3",
  ach_MELODIE_EVENT_3_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์ที่สามกับเมโลดี้",
  ach_RHYTHM_EVENT_1_name: "จังหวะของริทึ่ม 1",
  ach_RHYTHM_EVENT_1_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์แรกกับริทึ่ม",
  ach_RHYTHM_EVENT_2_name: "จังหวะของริทึ่ม 2",
  ach_RHYTHM_EVENT_2_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์ที่สองกับริทึ่ม",
  ach_RHYTHM_EVENT_3_name: "จังหวะของริทึ่ม 3",
  ach_RHYTHM_EVENT_3_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์ที่สามกับริทึ่ม",
  ach_HARMONIE_EVENT_1_name: "เสียงประสานของฮาร์โมนี่ 1",
  ach_HARMONIE_EVENT_1_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์แรกกับฮาร์โมนี่",
  ach_HARMONIE_EVENT_2_name: "เสียงประสานของฮาร์โมนี่ 2",
  ach_HARMONIE_EVENT_2_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์ที่สองกับฮาร์โมนี่",
  ach_HARMONIE_EVENT_3_name: "เสียงประสานของฮาร์โมนี่ 3",
  ach_HARMONIE_EVENT_3_desc: "ปลดล็อกเหตุการณ์ความสัมพันธ์ที่สามกับฮาร์โมนี่",
  ach_BECOME_LOVERS_MELODIE_name: "คนรักของเมโลดี้",
  ach_BECOME_LOVERS_MELODIE_desc: "คุณและเมโลดี้เป็นคนรักกันแล้ว",
  ach_BECOME_LOVERS_RHYTHM_name: "คนรักของริทึ่ม",
  ach_BECOME_LOVERS_RHYTHM_desc: "คุณและริทึ่มเป็นคนรักกันแล้วนะ",
  ach_BECOME_LOVERS_HARMONIE_name: "คนรักของฮาร์โมนี่",
  ach_BECOME_LOVERS_HARMONIE_desc: "คุณและฮาร์โมนี่เป็นคนรักกัน",
  ach_MARRIED_MELODIE_name: "แต่งงานกับเมโลดี้",
  ach_MARRIED_MELODIE_desc: "คุณและเมโลดี้แต่งงานกันแล้ว",
  ach_MARRIED_RHYTHM_name: "แต่งงานกับริทึ่ม",
  ach_MARRIED_RHYTHM_desc: "คุณและริทึ่มแต่งงานกันแล้ว",
  ach_MARRIED_HARMONIE_name: "แต่งงานกับฮาร์โมนี่",
  ach_MARRIED_HARMONIE_desc: "คุณและฮาร์โมนี่แต่งงานกันแล้ว",
  ach_REACH_LEVEL_10_name: "นักดนตรีผู้มุ่งมั่น",
  ach_REACH_LEVEL_10_desc: "ถึงเลเวล 10",
  ach_REACH_LEVEL_15_name: "ผู้เชี่ยวชาญด้านเสียง",
  ach_REACH_LEVEL_15_desc: "ถึงเลเวล 15",
  ach_STREAK_10_name: "หูทองคำ",
  ach_STREAK_10_desc: "ทำสถิติตอบถูกติดต่อกัน 10 ครั้ง",
  ach_STREAK_15_name: "เทพแห่งเสียง",
  ach_STREAK_15_desc: "ทำสถิติตอบถูกติดต่อกัน 15 ครั้ง",
  ach_COLLECT_500_GCOINS_name: "นักสะสมเหรียญ",
  ach_COLLECT_500_GCOINS_desc: "สะสม G-Coins ครบ 500 เหรียญ",
  ach_COLLECT_1000_GCOINS_name: "เศรษฐี G-Coins",
  ach_COLLECT_1000_GCOINS_desc: "สะสม G-Coins ครบ 1000 เหรียญ",
  ach_UNLOCK_FIRST_ADVANCED_ITEM_name: "ผู้ใฝ่รู้",
  ach_UNLOCK_FIRST_ADVANCED_ITEM_desc: "ปลดล็อกเนื้อหาดนตรีขั้นสูงชิ้นแรก",
  ach_PURCHASE_FIRST_SHOP_ITEM_name: "นักช้อปตัวยง",
  ach_PURCHASE_FIRST_SHOP_ITEM_desc: "ซื้อไอเทมชิ้นแรกจากร้านค้า",
  ach_ADOPT_FIRST_PET_name: "เพื่อนซี้สี่ขา",
  ach_ADOPT_FIRST_PET_desc: "รับเลี้ยงเพื่อนซี้ตัวแรก",
  ach_FEED_PET_FIRST_TIME_name: "มื้อแรกของเพื่อนซี้",
  ach_FEED_PET_FIRST_TIME_desc: "ให้อาหารเพื่อนซี้ครั้งแรก",
  ach_PET_REACH_LEVEL_5_name: "เพื่อนซี้เติบโต",
  ach_PET_REACH_LEVEL_5_desc: "เพื่อนซี้ถึงเลเวล 5",
  ach_PET_MAX_HAPPINESS_name: "เพื่อนซี้แฮปปี้สุดๆ",
  ach_PET_MAX_HAPPINESS_desc: "ความสุขของเพื่อนซี้เต็มเปี่ยม",
  ach_PET_PLAY_10_TIMES_name: "คู่หูนักเล่น",
  ach_PET_PLAY_10_TIMES_desc: "เล่นกับเพื่อนซี้ครบ 10 ครั้ง",
  ach_PET_COLLECTOR_name: "นักสะสมเพื่อนซี้",
  ach_PET_COLLECTOR_desc: `รับเลี้ยงเพื่อนซี้ครบทุกตัว (${PET_DEFINITIONS.filter(p => p.cost > 0 && !p.evolvesTo).length} ตัว)`,
  ach_PET_MAX_LEVEL_FIRST_name: "เพื่อนซี้มาสเตอร์",
  ach_PET_MAX_LEVEL_FIRST_desc: `เพื่อนซี้ถึงเลเวลสูงสุด (${MAX_PET_LEVEL})`,
  ach_PET_CUSTOMIZED_FIRST_name: "สไตล์ลิสต์เพื่อนซี้",
  ach_PET_CUSTOMIZED_FIRST_desc: "แต่งตัวให้เพื่อนซี้ครั้งแรก",
  ach_PET_FULFILL_REQUEST_FIRST_name: "เพื่อนซี้สมหวัง",
  ach_PET_FULFILL_REQUEST_FIRST_desc: "ทำตามคำขอพิเศษของเพื่อนซี้สำเร็จครั้งแรก",
  ach_FIRST_PET_EVOLUTION_name: "เพื่อนซี้แปลงร่าง!",
  ach_FIRST_PET_EVOLUTION_desc: "เพื่อนซี้พัฒนาร่างเป็นครั้งแรก",
  ach_M3_NOVICE_name: "ผู้เชี่ยวชาญ M3 ขั้นต้น",
  ach_M3_ADEPT_name: "ผู้เชี่ยวชาญ M3 ขั้นสูง",
  ach_MAJ_TRIAD_NOVICE_name: "ผู้เชี่ยวชาญคอร์ดเมเจอร์ขั้นต้น",
  ach_MAJ_TRIAD_ADEPT_name: "ผู้เชี่ยวชาญคอร์ดเมเจอร์ขั้นสูง",
  ach_MAJ9_INT_NOVICE_name: "เซียน Major 9th (Interval)",
  ach_MAJ9_CHORD_NOVICE_name: "เซียน Major 9th (Chord)",
  ach_FIRST_CORRECT_INTERVAL_name: "ก้าวแรกสู่ขั้นคู่",
  ach_FIRST_CORRECT_CHORD_name: "คอร์ดแรกก็มา",
  ach_FIRST_CORRECT_MELODY_name: "นักจำทำนองฝึกหัด",
  ach_REACH_LEVEL_5_name: "มือใหม่หัดฟัง",
  ach_FIRST_CORRECT_INTERVAL_desc: "ตอบคำถามเกี่ยวกับขั้นคู่เสียงถูกเป็นครั้งแรก",
  ach_STREAK_5_desc: "ทำสถิติตอบคำถามถูกติดต่อกัน 5 ครั้งในโหมดฝึกขั้นคู่หรือคอร์ด",
  ach_MELODY_RECALL_STREAK_3_desc: "เล่นทำนองตามได้ถูกต้องติดต่อกัน 3 ครั้ง",
  ach_MELODY_RECALL_STREAK_7_desc: "เล่นทำนองตามได้ถูกต้องติดต่อกัน 7 ครั้ง",
  ach_COLLECT_100_GCOINS_desc: "สะสม G-Coins ครบ 100 เหรียญ",
  ach_FIRST_CORRECT_CHORD_desc: "ตอบคำถามเกี่ยวกับคอร์ดถูกเป็นครั้งแรก",
  ach_FIRST_CORRECT_MELODY_desc: "เล่นทำนองตามได้ถูกต้องเป็นครั้งแรก",
  ach_REACH_LEVEL_5_desc: "ผู้เล่นถึงเลเวล 5",
  ach_STREAK_5_name: "ต่อเนื่องไปเลย!",
  ach_MELODY_RECALL_STREAK_3_name: "จำแม่น 3 โน้ต",
  ach_MELODY_RECALL_STREAK_7_name: "จำแม่น 7 โน้ต",
  ach_M3_NOVICE_desc: "ตอบถูกขั้นคู่ Major Third 10 ครั้ง",
  ach_M3_ADEPT_desc: "ตอบถูกขั้นคู่ Major Third 50 ครั้ง",
  ach_MAJ_TRIAD_NOVICE_desc: "ตอบถูกคอร์ด Major Triad 10 ครั้ง",
  ach_MAJ_TRIAD_ADEPT_desc: "ตอบถูกคอร์ด Major Triad 50 ครั้ง",
  ach_MAJ9_INT_NOVICE_desc: "ตอบถูกขั้นคู่ Major Ninth 10 ครั้ง",
  ach_MAJ9_CHORD_NOVICE_desc: "ตอบถูกคอร์ด Major Ninth 10 ครั้ง",
  ach_COMPLETE_FIRST_MISSION_name: "เริ่มทำภารกิจ",
  ach_COMPLETE_FIRST_MISSION_desc: "สำเร็จภารกิจแรกของคุณ",
  ach_COMPLETE_5_DAILY_MISSIONS_name: "กิจวัตรประจำวัน",
  ach_COMPLETE_5_DAILY_MISSIONS_desc: "สำเร็จภารกิจประจำวัน 5 ภารกิจ",
  ach_COMPLETE_FIRST_WEEKLY_MISSION_name: "ผู้พิชิตรายสัปดาห์",
  ach_COMPLETE_FIRST_WEEKLY_MISSION_desc: "สำเร็จภารกิจประจำสัปดาห์แรก",
  ach_DEFEAT_FIRST_MONSTER_name: "นักล่ามือใหม่",
  ach_DEFEAT_FIRST_MONSTER_desc: "ปราบอสูรดนตรีตัวแรก",
  ach_DEFEAT_MONO_NOTE_SLIME_name: "ผู้พิชิตสไลม์",
  ach_DEFEAT_MONO_NOTE_SLIME_desc: "ปราบโมโนโน้ตสไลม์",
  ach_DEFEAT_CHORD_CRACKER_name: "ผู้ทำลายแครกเกอร์",
  ach_DEFEAT_CHORD_CRACKER_desc: "ปราบคอร์ดแครกเกอร์",
  ach_DEFEAT_INTERVAL_IMP_name: "ผู้ปราบอิมพ์",
  ach_DEFEAT_INTERVAL_IMP_desc: "ปราบอินเทอร์วัลอิมพ์",
  ach_DEFEAT_RHYTHM_LORD_name: "ผู้โค่นเจ้าแห่งจังหวะ",
  ach_DEFEAT_RHYTHM_LORD_desc: "ปราบเจ้าแห่งจังหวะ",
  ach_DEFEAT_HARMONY_SIREN_name: "ผู้สยบไซเรน",
  ach_DEFEAT_HARMONY_SIREN_desc: "ปราบไซเรนแห่งฮาร์โมนี",
  ach_COLLECT_ALL_MEMENTOS_name: "นักสะสมของที่ระลึก",
  ach_COLLECT_ALL_MEMENTOS_desc: "รวบรวมของที่ระลึกจากอสูรทุกชนิด",
  ach_QUEST_ACCEPTED_FIRST_name: "นักผจญภัยหน้าใหม่",
  ach_QUEST_ACCEPTED_FIRST_desc: "รับเควสแรกของคุณ",
  ach_QUEST_COMPLETED_FIRST_name: "ผู้ไขปริศนา",
  ach_QUEST_COMPLETED_FIRST_desc: "ทำเควสแรกสำเร็จ",
  freestyleJamRoomTitle: "ห้องซ้อมดนตรีอิสระ",
  freestyleJamRoomDescription: "เล่นเปียโนได้อย่างอิสระ ลองสร้างทำนองเพลงของตัวเอง หรือจะใช้เพื่อฝึกฝนก็ได้นะ!",
  selectSoundLabel: "เลือกเสียงเครื่องดนตรี:",
  freestyleJamRoomButton: "ห้องซ้อมอิสระ",
  gameGuideTitle: "คู่มือการเล่น",
  gameGuide_MainGoal_Title: "เป้าหมายหลักของเกม",
  gameGuide_MainGoal_Desc: "พัฒนาทักษะการฟังเสียงดนตรีของคุณไปพร้อมกับสร้างชีวิตในโลกแห่งเสียงเพลง! ฝึกฝน สะสม G-Coins ปลดล็อกเนื้อหาใหม่ๆ และสร้างความสัมพันธ์กับตัวละครต่างๆ",
  gameGuide_Training_Title: "โหมดฝึกฝน",
  gameGuide_Training_Modes_Title: "ประเภทการฝึก",
  gameGuide_Training_Modes_Interval_Desc: "ฝึกการจดจำขั้นคู่เสียงต่างๆ",
  gameGuide_Training_Modes_Chord_Desc: "ฝึกการจดจำคอร์ดชนิดต่างๆ",
  gameGuide_Training_Difficulty_Title: "ระดับความยาก",
  gameGuide_Training_Difficulty_Desc: "แต่ละโหมดมีระดับความยากให้เลือก ซึ่งจะส่งผลต่อความซับซ้อนของโจทย์",
  gameGuide_Training_Rewards_Title: "รางวัลจากการฝึก",
  gameGuide_Training_Rewards_Desc: "การตอบถูกจะทำให้คุณได้รับ XP และ G-Coins ยิ่งทำสถิติติดต่อกันได้มาก รางวัลก็อาจจะเพิ่มขึ้น!",
  gameGuide_MonsterLair_Title: "ถ้ำอสูรดนตรี",
  gameGuide_MonsterLair_Desc: "ท้าทายอสูรดนตรีเพื่อทดสอบทักษะของคุณ! อสูรแต่ละตัวจะมีรูปแบบการโจมตี (โจทย์ดนตรี) ที่แตกต่างกัน",
  gameGuide_MonsterLair_Rewards_Title: "รางวัลจากอสูร",
  gameGuide_MonsterLair_Rewards_Desc: "เมื่อปราบอสูรได้ คุณจะได้รับ G-Coins, XP และมีโอกาสได้รับของที่ระลึก (Memento) ซึ่งเป็นไอเทมสำคัญสำหรับบางอย่าง",
  gameGuide_Pets_Title: "เพื่อนซี้ (สัตว์เลี้ยง)",
  gameGuide_Pets_Adoption_Title: "การรับเลี้ยง",
  gameGuide_Pets_Adoption_Desc: "คุณสามารถรับเลี้ยงเพื่อนซี้ได้จากศูนย์รับเลี้ยง ใช้ G-Coins ในการรับเลี้ยงนะ",
  gameGuide_Pets_Care_Title: "การดูแล",
  gameGuide_Pets_Care_Desc: "เพื่อนซี้ต้องการอาหารและความเอาใจใส่ อย่าลืมให้อาหารและเล่นกับพวกเขาบ่อยๆ เพื่อเพิ่มความสุขและค่าประสบการณ์",
  gameGuide_Pets_Abilities_Title: "ความสามารถพิเศษ",
  gameGuide_Pets_Abilities_Desc: "เพื่อนซี้แต่ละตัวมีความสามารถพิเศษที่แตกต่างกัน ซึ่งจะช่วยในการเล่นเกมของคุณเมื่อพวกเขามีความสุขและเลเวลถึงกำหนด",
  gameGuide_MyHome_Title: "บ้านของฉัน",
  gameGuide_MyHome_Upgrade_Title: "การอัปเกรดบ้าน",
  gameGuide_MyHome_Upgrade_Desc: "คุณสามารถใช้ G-Coins เพื่ออัปเกรดบ้านของคุณได้ บ้านที่ระดับสูงขึ้นจะมอบโบนัสต่างๆ เช่น G-Coins เพิ่มจากรางวัลล็อกอินรายวัน",
  gameGuide_MyHome_Furniture_Title: "เฟอร์นิเจอร์",
  gameGuide_MyHome_Furniture_Desc: "ซื้อเฟอร์นิเจอร์มาตกแต่งบ้านเพื่อรับโบนัสพิเศษเพิ่มเติม เช่น เพิ่ม XP จากการฝึก หรือส่วนลดในการซื้อของ",
  gameGuide_MyHome_PracticeNook_Title: "มุมซ้อมดนตรี",
  gameGuide_MyHome_PracticeNook_Desc: "ใช้มุมซ้อมดนตรีในบ้านเพื่อรับ XP เล็กน้อยและเพิ่มความสุขให้เพื่อนซี้ มี Cooldown หลังการใช้งานแต่ละครั้ง",
  gameGuide_Missions_Title: "ภารกิจ",
  gameGuide_Missions_Desc: "ทำภารกิจประจำวันและประจำสัปดาห์ให้สำเร็จเพื่อรับรางวัลมากมาย ทั้ง G-Coins, XP ผู้เล่น, และ XP เพื่อนซี้",
  gameGuide_FreestyleJamRoom_Title: "ห้องซ้อมอิสระ",
  gameGuide_FreestyleJamRoom_Desc: "มาปลดปล่อยความเป็นศิลปินในตัวคุณ! เล่นเปียโนได้อย่างอิสระ ไม่มีโจทย์ ไม่มีคะแนน มีแต่ความสนุกและความคิดสร้างสรรค์",
  gameGuide_GCoins_Shop_Title: "G-Coins และร้านค้า",
  gameGuide_GCoins_Shop_GCoins_Title: "G-Coins",
  gameGuide_GCoins_Shop_GCoins_Desc: "สกุลเงินหลักในเกม ใช้สำหรับซื้อไอเทม อัปเกรด และปลดล็อกเนื้อหาต่างๆ หาได้จากการฝึกฝน, ทำภารกิจ, และปราบอสูร",
  gameGuide_GCoins_Shop_Shop_Title: "ร้านค้าไอเทม",
  gameGuide_GCoins_Shop_Shop_Desc: "ที่นี่คุณสามารถซื้อไอเทมจำเป็นต่างๆ เช่น อาหารเพื่อนซี้, เสียงเครื่องดนตรีใหม่, หรือของตกแต่ง",
  gameGuide_GCoins_Shop_Unlockables_Title: "ปลดล็อกเนื้อหาดนตรี",
  gameGuide_GCoins_Shop_Unlockables_Desc: "ใช้ G-Coins เพื่อปลดล็อกขั้นคู่เสียงและคอร์ดขั้นสูง ทำให้คุณสามารถฝึกฝนเนื้อหาที่ท้าทายยิ่งขึ้นได้",
  gameGuide_Progression_Title: "ความก้าวหน้าในเกม",
  gameGuide_Progression_PlayerLevel_Title: "เลเวลผู้เล่น",
  gameGuide_Progression_PlayerLevel_Desc: "เพิ่ม XP จากการทำกิจกรรมต่างๆ เพื่อเพิ่มเลเวล ปลดล็อกความสามารถใหม่ๆ หรือเนื้อหาเพิ่มเติม",
  gameGuide_Progression_Achievements_Title: "ความสำเร็จ",
  gameGuide_Progression_Achievements_Desc: "ทำตามเป้าหมายต่างๆ ในเกมเพื่อปลดล็อกความสำเร็จและรับรางวัลพิเศษ (ถ้ามี)",
  gameGuide_Progression_Monsterpedia_Title: "สารานุกรมอสูร",
  gameGuide_Progression_Monsterpedia_Desc: "เมื่อคุณปราบอสูรได้ ข้อมูลของมันจะถูกบันทึกไว้ที่นี่ รวมถึงของที่ระลึกที่คุณเก็บได้ด้วย",
  viewGameGuide: "คู่มือการเล่น",
  npcHubTitle: "ศูนย์รวม NPC",
  questInteractionTitle: "ปฏิสัมพันธ์เควส",
  npc_MUSIC_MASTER_name: "ปรมาจารย์ดนตรี",
  npc_MEMENTO_COLLECTOR_name: "นักสะสมของเก่า",
  npc_ZALAY_BEAT_name: "ZALAY BEAT",
  npc_MELODIE_name: "เมโลดี้",
  npc_RHYTHM_name: "ริทึ่ม",
  npc_HARMONIE_name: "ฮาร์โมนี่",
  quest_LOST_MUSIC_SHEET_MUSIC_MASTER_title: "โน้ตเพลงที่หายไป",
  quest_LOST_MUSIC_SHEET_MUSIC_MASTER_desc: "ปรมาจารย์ดนตรีทำโน้ตเพลงสำคัญหายไป ช่วยเขตามหาหน่อย!",
  quest_LOST_MUSIC_SHEET_MUSIC_MASTER_obj1: "พูดคุยกับปรมาจารย์ดนตรีเกี่ยวกับโน้ตเพลงที่หายไป",
  quest_LOST_MUSIC_SHEET_MUSIC_MASTER_obj_collect_clues: "รวบรวมเบาะแสเกี่ยวกับโน้ตเพลง 3 ชิ้น",
  quest_LOST_MUSIC_SHEET_MUSIC_MASTER_obj_solve_puzzle: "ไขปริศนาตำแหน่งของโน้ตเพลง",
  quest_LOST_MUSIC_SHEET_MUSIC_MASTER_obj_defeat_imp: "ปราบอินเทอร์วัลอิมพ์ที่อาจจะเก็บโน้ตเพลงไว้",
  quest_LOST_MUSIC_SHEET_MUSIC_MASTER_obj_retrieve_sheet: "ค้นหาและเก็บโน้ตเพลงที่หายไป",
  npcMusicMasterLostSheetThanks: "ขอบคุณมากที่ช่วยหาโน้ตเพลงจนเจอ! เพลงนี้มีความหมายกับข้ามากจริงๆ",
  quest_NEW_PET_TRAINING_MUSIC_MASTER_title: "การฝึกฝนเพื่อนซี้มือใหม่",
  quest_NEW_PET_TRAINING_MUSIC_MASTER_desc: "ปรมาจารย์ดนตรีอยากสอนวิธีดูแลเพื่อนซี้เบื้องต้นให้คุณ",
  quest_NEW_PET_TRAINING_MUSIC_MASTER_obj_talk: "พูดคุยกับปรมาจารย์ดนตรีเกี่ยวกับการฝึกเพื่อนซี้",
  quest_NEW_PET_TRAINING_MUSIC_MASTER_obj_learn: "เรียนรู้วิธีให้อาหารและเล่นกับเพื่อนซี้",
  quest_NEW_PET_TRAINING_MUSIC_MASTER_obj_collect_food: "รวบรวมอาหารพิเศษสำหรับเพื่อนซี้ 1 ชิ้น",
  quest_NEW_PET_TRAINING_MUSIC_MASTER_obj_feed_pet: "ให้อาหารพิเศษแก่เพื่อนซี้ของคุณ",
  npcMusicMasterNewPetTrainingDialogue: "การดูแลเพื่อนซี้ก็เหมือนการประพันธ์เพลง ต้องใส่ใจและเข้าใจพวกเขา เจ้าพร้อมจะเรียนรู้รึยัง?",
  npcMusicMasterNewPetTrainingThanks: "เยี่ยมมาก! เจ้าเรียนรู้ได้รวดเร็ว ข้าหวังว่าเจ้าจะดูแลเพื่อนซี้ของเจ้าเป็นอย่างดีนะ",
  item_LOST_CLUE_NAME: "เบาะแสโน้ตเพลง",
  item_LOST_MUSIC_SHEET_NAME: "โน้ตเพลงโบราณ",
  item_SPECIAL_PET_FOOD_NAME: "อาหารเพื่อนซี้สูตรพิเศษ",
  item_SLIME_ESSENCE_ITEM_ID_NAME: "แก่นสไลม์ (ไอเทมเควส)",
  song_ANCIENT_MELODY_NAME: "ทำนองโบราณ",
  viewNPCHub: "ศูนย์รวม NPC",
  viewAvatarCustomization: "ปรับแต่งตัวละคร",
  questAcceptButton: "รับเควส",
  questInProgressLabel: "กำลังดำเนินเควส...",
  questCompletedLabel: "เควสสำเร็จ!",
  questClaimRewardButton: "รับรางวัลเควส",
  questRewardsLabel: "รางวัล:",
  questObjectivesLabel: "เป้าหมาย:",
  questStartedNotificationTitle: "เริ่มเควสใหม่!",
  questObjectiveCompletedNotificationTitle: "เป้าหมายสำเร็จ!",
  questCompletedNotificationTitle: "เควสสำเร็จ!",
  questRewardClaimedNotificationTitle: "รับรางวัลเควสแล้ว!",
  npcGenericGreeting: "สวัสดี มีอะไรให้ช่วยไหม?",
  npcMusicMasterGreeting: "ยินดีต้อนรับสู่โลกแห่งเสียงเพลง มีอะไรให้ข้าสอนเจ้ารึ?",
  npcMementoCollectorGreeting: "อืมมม... มีของหายากมาให้ข้าดูรึเปล่าล่ะ?",
  npcZalayBeatGreeting: "โย่ว! ว่าไงเพื่อน! พร้อมจะสร้างบีทมันส์ๆ หรือยัง?",
  npcMusicMasterLostSheetDialogue: "แย่แล้ว! ข้าทำโน้ตเพลงสำคัญหายไปน่ะสิ มันเป็นเพลงโบราณที่หายากมาก เจ้าพอจะช่วยข้าตามหาได้หรือไม่?",
  npcNoQuestsAvailable: "ตอนนี้ยังไม่มีอะไรให้ช่วยนะ ลองกลับมาใหม่วันหลัง",
  melodieInteractionPrompt: "คุณอยากจะทำอะไรกับเมโลดี้?",
  relationshipJournalTitle: "สมุดบันทึกความสัมพันธ์",
  viewRelationshipJournal: "ดูสมุดความสัมพันธ์",
  melodieRPStatus: "เมโลดี้: {rp}/100 RP",
  rhythmRPStatus: "ริทึ่ม: {rp}/100 RP",
  harmonieRPStatus: "ฮาร์โมนี่: {rp}/100 RP",
  relationshipIncreased: "ความสัมพันธ์กับ {npcName} เพิ่มขึ้น!",
  relationshipDecreased: "ความสัมพันธ์กับ {npcName} ลดลง...",
  relationshipMelodieFeelsDistant: "เมโลดี้ดูห่างเหิน... ลองไปคุยกับเธอบ่อยๆ นะ",
  relationshipRhythmFeelsDistant: "ริทึ่มดูห่างเหินไปนะ ลองไปคุยกับเขาบ่อยๆ",
  relationshipHarmonieFeelsDistant: "ฮาร์โมนี่ดูเงียบขรึมกว่าปกติ ลองไปคุยกับเธอบ้างนะ",
  melodieInteractionPageTitle: "พูดคุยกับเมโลดี้",
  rhythmInteractionPageTitle: "พูดคุยกับริทึ่ม",
  harmonieInteractionPageTitle: "พูดคุยกับฮาร์โมนี่",
  talkButtonLabel: "พูดคุย",
  giveGiftButtonLabel: "ให้ของขวัญ",
  melodiePortraitAltText: "รูปภาพเมโลดี้",
  rhythmPortraitAltText: "รูปภาพริทึ่ม",
  harmoniePortraitAltText: "รูปภาพฮาร์โมนี่",
  giftingPageTitle: "ให้ของขวัญแก่ {npcName}",
  selectGiftPrompt: "เลือกของขวัญที่จะให้:",
  giftButtonLabel: "มอบของขวัญ",
  noMementosToGift: "คุณไม่มีของที่ระลึกจากอสูรเลย",
  giftSuccessMessage: "{npcName} ดูเหมือนจะชอบของขวัญของคุณนะ!",
  giftFailMessage: "ดูเหมือน {npcName} จะไม่ค่อยสนใจของขวัญชิ้นนี้เท่าไหร่",
  giftGivenNotification: "คุณมอบ {giftName} ให้กับ {npcName}",
  genericNPCInteractionPageTitle: "ปฏิสัมพันธ์กับ NPC",
  confessFeelingsButtonLabel: "สารภาพความรู้สึก",
  confessionRequirementLocket: "คุณต้องมี 'จี้รูปหัวใจโน้ตดนตรี' เพื่อสารภาพรัก",
  confessionSuccessMelodie: "เมโลดี้รับความรู้สึกของคุณแล้ว! ตอนนี้คุณสองคนเป็นคนรักกัน",
  confessionSuccessRhythm: "ริทึ่มตอบรับความรู้สึกของคุณ! คุณกับเขาเป็นคนรักกันแล้วนะ",
  confessionSuccessHarmonie: "ฮาร์โมนี่เปิดใจรับความรู้สึกของคุณ ตอนนี้คุณสองคนเป็นคนรักกัน",
  relationshipStatusFriendly: "เพื่อนสนิท",
  relationshipStatusDating: "คนรัก",
  relationshipStatusMarried: "คู่สมรส",
  shopItem_HEART_NOTE_LOCKET_name: "จี้รูปหัวใจโน้ตดนตรี",
  shopItem_HEART_NOTE_LOCKET_desc: "จี้สวยงามสำหรับมอบให้คนที่คุณรู้สึกพิเศษด้วย",
  shopItem_WEDDING_RING_name: "แหวนแต่งงาน",
  shopItem_WEDDING_RING_desc: "แหวนสำหรับขอคนที่คุณรักแต่งงาน",
  proposeButtonLabel: "ขอแต่งงาน",
  proposeRequirementRing: "คุณต้องมี 'แหวนแต่งงาน' เพื่อขอแต่งงาน",
  proposeRequirementHouseLevel: "บ้านของคุณต้องมีระดับ 2 ขึ้นไปถึงจะขอแต่งงานได้",
  proposalSuccessMelodie: "เมโลดี้ตอบตกลง! คุณสองคนจะใช้ชีวิตร่วมกันแล้วนะ",
  proposalSuccessRhythm: "ริทึ่มตอบตกลง! เตรียมตัวสำหรับชีวิตคู่ได้เลย",
  proposalSuccessHarmonie: "ฮาร์โมนี่ตอบตกลง! คุณกับเธอจะสร้างครอบครัวด้วยกัน",
  datingRPStatus: "คนรัก ({rp}/{maxRp} RP)",
  genericError: "เกิดข้อผิดพลาดบางอย่าง",
  marriageHappinessDisplay: "ความสุขชีวิตคู่: {value}/100",
  spousalBonusMelodieDesc: "เมโลดี้ช่วยลดเวลา Cooldown ของมุมซ้อมดนตรี {value}%",
  spousalBonusRhythmDesc: "ริทึ่มมีโอกาสหา G-Coins พิเศษให้คุณ {value} เหรียญ!",
  spousalBonusHarmonieDesc: "ฮาร์โมนี่ช่วยเพิ่มโอกาสดรอป Memento หายาก {value}%",
  marriageHappinessSickAtHeart: "{npcName} ดูไม่ค่อยมีความสุขเลย... ลองใส่ใจเขา/เธอให้มากขึ้นนะ",
  relationshipEventTriggered: "มีเหตุการณ์พิเศษเกิดขึ้นกับ {npcName}!",
  eventDialogueContinueButton: "ดำเนินเรื่องต่อ",
  npcMelodiePersonalitySnippet: "สาวหวาน อ่อนโยน รักเสียงดนตรีคลาสสิกและการทำขนม",
  npcMelodieLikesSnippet: "เค้ก, ชาดอกไม้, โน้ตเพลงเก่าๆ",
  npcMelodieGoalSnippet: "อยากเปิดร้านเบเกอรี่เล็กๆ ที่มีเสียงเพลงบรรเลง",
  npcRhythmPersonalitySnippet: "หนุ่มมั่นใจ ไฟแรง ชอบดนตรีร็อคและการผจญภัย",
  npcRhythmLikesSnippet: "ของเผ็ดๆ, เครื่องดนตรีไฟฟ้า, แผนที่ใหม่ๆ",
  npcRhythmGoalSnippet: "อยากเป็นนักดนตรีร็อคชื่อดังระดับโลก",
  npcHarmoniePersonalitySnippet: "สาวลึกลับ พูดน้อย ชอบดนตรีแนว Ambient และดวงดาว",
  npcHarmonieLikesSnippet: "หนังสือเก่า, ชาสมุนไพร, ของสะสมแปลกๆ",
  npcHarmonieGoalSnippet: "อยากค้นพบความลับของเสียงดนตรีในจักรวาล",
  npcLikesLabel: "ชอบ:",
  npcGoalLabel: "เป้าหมาย:",
  melodie_event_rp25_dialogue: "เมโลดี้: 'วันนี้อากาศดีจังเลยนะคะ อยากไปเดินเล่นในสวนจัง'",
  melodie_event_rp50_dialogue: "เมโลดี้: 'ฉันลองทำเค้กสูตรใหม่มาค่ะ อยากให้คุณลองชิมจังเลย'",
  melodie_event_rp75_dialogue: "เมโลดี้: 'เพลงที่คุณเล่นเมื่อกี้... มันทำให้ฉันรู้สึกอบอุ่นหัวใจมากเลยค่ะ'",
  melodie_dialogue_dating_default: "เมโลดี้: '{playerName} ที่รัก วันนี้มีอะไรอยากเล่าให้ฉันฟังไหมคะ?'",
  melodie_dialogue_married_happy: "เมโลดี้: 'กลับมาแล้วเหรอคะ {playerName} วันนี้ฉันทำ {randomDish} ไว้ให้ด้วยนะ!'",
  melodie_dialogue_married_sick_at_heart: "เมโลดี้: '{playerName}... ฉันรู้สึกไม่ค่อยสบายใจเลยค่ะช่วงนี้'",
  randomDishMelodie1: "สตรอว์เบอร์รีชอร์ตเค้ก",
  randomDishMelodie2: "คุกกี้อัลมอนด์",
  randomDishMelodie3: "มัฟฟินบลูเบอร์รี่",
  rhythm_event_rp25_dialogue: "ริทึ่ม: 'โย่ว! ว่าไงเพื่อน! ว่างๆ ไปแจมดนตรีกันหน่อยมะ?'",
  rhythm_event_rp50_dialogue: "ริทึ่ม: 'ฉันเพิ่งแต่งเพลงใหม่เสร็จ อยากให้นายลองฟังเป็นคนแรกเลยว่ะ'",
  rhythm_event_rp75_dialogue: "ริทึ่ม: 'เวลาอยู่กับนายแล้วมัน... รู้สึกดีแปลกๆ ว่ะ ไม่เหมือนอยู่กับคนอื่นเลย'",
  rhythm_dialogue_dating_default: "ริทึ่ม: 'เฮ้ {playerName}! วันนี้เราจะไปสร้างตำนานอะไรกันดีล่ะ?'",
  rhythm_dialogue_married_happy: "ริทึ่ม: 'กลับมาแล้วเหรอ {playerName}! มามะ มาให้กำลังใจหน่อย กำลังคิดเพลงใหม่อยู่เลย!'",
  rhythm_dialogue_married_sick_at_heart: "ริทึ่ม: '{playerName} นายว่า... เรายังโอเคกันอยู่รึเปล่าวะ?'",
  harmonie_event_rp25_dialogue: "ฮาร์โมนี่: '...ดวงดาวคืนนี้สวยดีนะ'",
  harmonie_event_rp50_dialogue: "ฮาร์โมนี่: 'ฉันเจอหนังสือเล่มนี้น่าสนใจ... คุณอยากอ่านด้วยกันไหม?'",
  harmonie_event_rp75_dialogue: "ฮาร์โมนี่: 'เสียงเพลงของคุณ... มันทำให้ฉันรู้สึก... ปลอดภัย'",
  harmonie_dialogue_dating_default: "ฮาร์โมนี่: '{playerName}... วันนี้... อยากทำอะไรด้วยกันไหม?'",
  harmonie_dialogue_married_happy: "ฮาร์โมนี่: 'ยินดีต้อนรับกลับ {playerName}... ฉันชงชาสมุนไพรสูตรพิเศษไว้ให้'",
  harmonie_dialogue_married_sick_at_heart: "ฮาร์โมนี่: '{playerName}... บางที... ความเงียบก็เสียงดังเกินไป'",
  shopItem_FLOWER_BOUQUET_name: "ช่อดอกไม้",
  shopItem_FLOWER_BOUQUET_desc: "ช่อดอกไม้สวยงาม สื่อถึงความรู้สึกดีๆ",
  shopItem_CHOCOLATE_BOX_name: "กล่องช็อกโกแลต",
  shopItem_CHOCOLATE_BOX_desc: "ช็อกโกแลตหลากหลายรสชาติ หวานอร่อย",
  shopItem_SPICY_SNACKS_name: "ขนมรสเผ็ด",
  shopItem_SPICY_SNACKS_desc: "ขนมขบเคี้ยวรสชาติจัดจ้าน",
  shopItem_OLD_BOOK_name: "หนังสือเก่า",
  shopItem_OLD_BOOK_desc: "หนังสือหายากที่มีเรื่องราวน่าค้นหา",
  shopItem_TEA_SET_name: "ชุดชา",
  shopItem_TEA_SET_desc: "ชุดชาคุณภาพดี เหมาะสำหรับช่วงเวลาผ่อนคลาย",
  shopItem_HANDMADE_COOKIE_name: "คุกกี้ทำเอง",
  shopItem_HANDMADE_COOKIE_desc: "คุกกี้อบใหม่ๆ หอมกรุ่นจากเตา",
  giftReactionLoved: "{npcName} ดูมีความสุขกับของขวัญชิ้นนี้มาก!",
  giftReactionLiked: "{npcName} ยิ้มรับของขวัญของคุณ",
  giftReactionNeutral: "{npcName} รับของขวัญของคุณไว้",
  giftReactionDisliked: "{npcName} ดูจะไม่ค่อยชอบของขวัญชิ้นนี้เท่าไหร่...",
  selectAnyGiftPrompt: "คุณสามารถให้ของขวัญได้ทั้ง Mementos และไอเทมจากร้านค้า",
  childNamingPageTitle: "ตั้งชื่อลูกน้อย",
  childNamingPromptGeneric: "คุณกำลังจะมีสมาชิกใหม่ในครอบครัว! โปรดตั้งชื่อให้ลูกของคุณ:",
  childNamingPromptWithSpouse: "คุณและ {spouseName} กำลังจะมีสมาชิกใหม่ในครอบครัว! มาช่วยกันตั้งชื่อที่แสนวิเศษให้เขากันเถอะ",
  childNamePlaceholder: "ชื่อลูก...",
  childNameSubmitButton: "ยืนยันชื่อ",
  childNameErrorEmpty: "ชื่อลูกห้ามว่าง",
  childNameErrorTooLong: "ชื่อลูกต้องไม่เกิน 15 ตัวอักษร",
  cancelButtonLabel: "ยกเลิก",
  familyEventInProgressTitle: "กิจกรรมครอบครัว",
  familyChildNamingPrompt: "ตั้งชื่อให้ลูกของคุณกับ {npcName}",
  familyChildBornTitle: "สมาชิกใหม่!",
  familyChildBornMessage: "ยินดีด้วย! คุณและ {npcName} ได้ต้อนรับ {childName} สู่ครอบครัว!",
  feedChildNotification: "คุณป้อนอาหารให้ {childName}",
  playWithChildNotification: "คุณเล่นกับ {childName} อย่างสนุกสนาน",
  changeDiaperNotification: "คุณเปลี่ยนผ้าอ้อมให้ {childName} เรียบร้อยแล้ว",
  sootheToSleepNotification: "{childName} หลับปุ๋ยไปแล้ว...",
  childCareKitUsedNotification: "คุณใช้ชุดดูแลเด็กกับ {childName}",
  childRecoveredNotification: "{childName} หายป่วยแล้ว!",
  childSickNotification: "{childName} ดูเหมือนจะไม่สบายนะ!",
  childIsSickMessage: "{childName} ไม่สบาย ต้องการการดูแลเป็นพิเศษ",
  useChildCareKitButtonLabel: "ใช้ชุดดูแล",
  sootheToSleepButtonLabel: "กล่อมหลับ",
  shopItem_BABY_CRIB_name: "เตียงเด็ก",
  shopItem_BABY_CRIB_desc: "เตียงนอนแสนสบายสำหรับลูกน้อยของคุณ",
  shopItem_MILK_POWDER_name: "นมผง",
  shopItem_MILK_POWDER_desc: "นมผงสำหรับทารก ให้สารอาหารครบถ้วน",
  shopItem_BABY_FOOD_name: "อาหารเด็ก",
  shopItem_BABY_FOOD_desc: "อาหารบดละเอียดสำหรับเด็กโตขึ้นมาหน่อย",
  shopItem_DIAPERS_name: "ผ้าอ้อม",
  shopItem_DIAPERS_desc: "ผ้าอ้อมสำเร็จรูป ช่วยให้ลูกน้อยสบายตัว",
  shopItem_CHILD_CARE_KIT_name: "ชุดดูแลเด็กป่วย",
  shopItem_CHILD_CARE_KIT_desc: "ชุดไอเทมจำเป็นสำหรับดูแลลูกน้อยเมื่อไม่สบาย",
  childCareItemsCategory: "ไอเทมดูแลเด็ก",
  childGrowthStage_INFANT: "ทารก",
  childGrowthStage_CRAWLER: "เด็กหัดคลาน",
  childGrowthStage_TODDLER: "เด็กหัดเดิน",
  childGrowthStage_SCHOOL_AGE: "เด็กวัยเรียน",
  childGrowsTitle: "ลูกของคุณเติบโตขึ้น!",
  childGrowsToCrawlerMessage: "{childName} ตอนนี้เริ่มคลานได้แล้วนะ!",
  childGrowsToToddlerMessage: "{childName} เริ่มหัดเดินแล้ว! น่าตื่นเต้นจริงๆ!",
  childHappinessLabel: "ความสุข:",
  childHungerLabel: "ความหิว:",
  childCleanlinessLabel: "ความสะอาด:",
  childAffectionLabel: "ความรัก:",
  childSleepinessLabel: "ความง่วง:",
  feedChildButton: "ป้อนอาหาร",
  playWithChildButton: "เล่นด้วย",
  changeDiaperButton: "เปลี่ยนผ้าอ้อม",
  childNeedHungry: "{childName} หิวแล้ว ต้องการอาหาร!",
  childNeedDirty: "{childName} ต้องการการทำความสะอาด!",
  childNeedAffection: "{childName} ต้องการความรักความเอาใจใส่!",
  childNeedSleepy: "{childName} ดูง่วงนอนมากแล้ว พาไปนอนเถอะ",
  notEnoughItemToCareChild: "คุณไม่มี {itemName} เพียงพอ",
  ach_HAVE_FIRST_CHILD_name: "ครอบครัวตัว อ. (อู๊ดๆ)",
  ach_HAVE_FIRST_CHILD_desc: "มีลูกคนแรก",
  ach_CHILD_FIRST_WORDS_name: "คำแรกของหนู",
  ach_CHILD_FIRST_WORDS_desc: "ลูกของคุณเริ่มพูดคำแรกได้แล้ว",
  ach_CHILD_FIRST_STEPS_name: "ก้าวแรกที่มั่นคง",
  ach_CHILD_FIRST_STEPS_desc: "ลูกของคุณเริ่มเดินได้แล้ว",
  goOnDateButtonLabel: "ไปเดท",
  dateSuccessMessage: "คุณไปเดทกับ {npcName} อย่างมีความสุข!",
  payTuitionButtonLabel: "จ่ายค่าเล่าเรียน",
  helpWithHomeworkButtonLabel: "ช่วยทำการบ้าน",
  academicPerformanceLabel: "ผลการเรียน:",
  tuitionStatusLabel: "สถานะค่าเล่าเรียน:",
  tuitionStatusDue: "ถึงกำหนดชำระ",
  tuitionStatusOverdue: "ค้างชำระ",
  tuitionStatusPaid: "ชำระแล้ว",
  tuitionPaidSuccess: "จ่ายค่าเล่าเรียนให้ {childName} จำนวน {tuitionAmount} G-Coins เรียบร้อยแล้ว",
  tuitionPaymentFailedNotEnoughGcoins: "{childName} ยังไม่ได้จ่ายค่าเล่าเรียน! G-Coins ไม่เพียงพอ",
  tuitionOverdueNotification: "แจ้งเตือน: ค่าเล่าเรียนของ {childName} ({tuitionAmount} G) เลยกำหนดชำระแล้ว!",
  homeworkAvailableNotification: "{childName} มีการบ้าน! อย่าลืมช่วยนะ",
  homeworkHelpedSuccess: "คุณช่วย {childName} ทำการบ้านสำเร็จแล้ว!",
  childStartsSchoolNotification: "{childName} โตพอที่จะเข้าโรงเรียนแล้ว! อย่าลืมดูแลเรื่องค่าเล่าเรียนและการบ้านนะ",
  sideJobBuskingTitle: "เล่นดนตรีเปิดหมวก",
  sideJobBuskingDescription: "แสดงความสามารถทางดนตรีของคุณในที่สาธารณะเพื่อหารายได้เสริมเล็กน้อย",
  sideJobBuskingSuccessMessage: "คุณเล่นดนตรีเปิดหมวกจบแล้ว! ได้รับ {gcoinsEarned} G-Coins!",
  sideJobOnCooldownMessage: "กำลังพักคอ/พักนิ้ว! รออีก {itemName}",
  sideJobPerformBuskingButton: "เริ่มเล่นดนตรีเปิดหมวก",
  familyActivityButtonLabel: "กิจกรรมครอบครัว",
  familyActivityParkTripName: "ไปเที่ยวสวนสาธารณะ",
  familyActivityParkTripSuccessMessage: "ครอบครัวของคุณไปเที่ยวสวนสาธารณะอย่างมีความสุข!",
  familyActivityOnCooldownMessage: "กิจกรรมนี้ยังอยู่ในช่วงพัก {itemName}",
  familyActivityRequiresSpouseAndChildMessage: "คุณต้องแต่งงานและมีลูกก่อนถึงจะทำกิจกรรมครอบครัวได้",
  familyActivityRequiresGcoinsMessage: "G-Coins ไม่พอสำหรับกิจกรรมนี้ ({gcoinsSpent} G)",
  // petSpecialRequestExpiredMessage: "คำขอของ {petName} หมดอายุแล้ว ดูเหมือน {petName} จะเสียใจนะ...", // Removed duplicate
  // petAbilityDisabledLowHappinessMessage: "ความสามารถของ {petName} ไม่ทำงานเนื่องจากความสุขต่ำเกินไป", // Removed duplicate
  npcMusicMasterPersonalitySnippet: "ปรมาจารย์ดนตรีโบราณ ผู้เปี่ยมด้วยความรู้และเมตตา",
  npcMusicMasterLikesSnippet: "ความเงียบสงบ, เสียงธรรมชาติ, ความพยายามของศิษย์",
  npcMusicMasterGoalSnippet: "ถ่ายทอดความรู้ด้านดนตรีให้คนรุ่นหลัง",
  npcMementoCollectorPersonalitySnippet: "นักสะสมผู้ลึกลับ สนใจของเก่าและเรื่องราวเบื้องหลัง",
  npcMementoCollectorLikesSnippet: "ของหายาก, เรื่องเล่าโบราณ, ความเงียบ",
  npcMementoCollectorGoalSnippet: "รวบรวม Memento ทั้งหมดเพื่อไขความลับบางอย่าง",
  npcZalayBeatPersonalitySnippet: "AI สุดล้ำ ทันสมัย เชี่ยวชาญด้านเทคโนโลยีดนตรี",
  npcZalayBeatLikesSnippet: "บีทใหม่ๆ, อุปกรณ์อิเล็กทรอนิกส์, การทดลองเสียง",
  npcZalayBeatGoalSnippet: "สร้างสุดยอด AI Producer ที่เข้าใจทุกแนวดนตรี",
  academicPerformanceImprovedMessage: "ผลการเรียนของ {childName} ดีขึ้นเป็น {newGrade}!",
  academicPerformanceDeclinedMessage: "ผลการเรียนของ {childName} แย่ลงเป็น {newGrade}...",
  teacherMeetingNotification: "แจ้งเตือนจากโรงเรียน: ครูต้องการพบผู้ปกครองของ {childName} เกี่ยวกับผลการเรียน",
  sideJobFamilyUnhappyMessage: "คุณไม่มีอารมณ์ทำงานเสริมในตอนนี้ ครอบครัวต้องการการดูแล...",
  birthdayNotificationTitle: "สุขสันต์วันเกิด!",
  childBirthdayMessage: "วันนี้เป็นวันเกิดของ {childName}! อย่าลืมฉลองให้เขานะ",
  spouseBirthdayMessage: "วันนี้เป็นวันเกิดของ {spouseName}! หาอะไรพิเศษให้เขา/เธอหน่อยสิ",
  buyBirthdayCakeButtonLabel: "ซื้อเค้กวันเกิด ({cost} G)",
  celebrateBirthdaySuccessMessage: "คุณฉลองวันเกิดให้ {targetName} อย่างมีความสุข!",
  familyNeglectMessage: "คุณละเลยครอบครัว ความสัมพันธ์และความสุขลดลง...",
  shopItem_BIRTHDAY_CAKE_name: "เค้กวันเกิด",
  shopItem_BIRTHDAY_CAKE_desc: "เค้กแสนอร่อยสำหรับฉลองวันพิเศษ",
  quest_INTRO_MELODIE_title: "ทำความรู้จักเมโลดี้",
  quest_INTRO_MELODIE_desc: "ไปพูดคุยทำความรู้จักกับเมโลดี้ที่ร้านกาแฟ",
  quest_INTRO_MELODIE_obj1: "ไปที่ร้านกาแฟและพูดคุยกับเมโลดี้",
  quest_INTRO_MELODIE_thanks: "ดีใจที่ได้คุยกับคุณนะคะ!",
  quest_INTRO_RHYTHM_title: "ทำความรู้จักริทึ่ม",
  quest_INTRO_RHYTHM_desc: "ไปพูดคุยทำความรู้จักกับริทึ่มที่ลานฝึกซ้อม",
  quest_INTRO_RHYTHM_obj1: "ไปที่ลานฝึกซ้อมและพูดคุยกับริทึ่ม",
  quest_INTRO_RHYTHM_thanks: "โย่ว! คุยกันมันส์ดี ไว้เจอกันใหม่นะ!",
  quest_INTRO_HARMONIE_title: "ทำความรู้จักฮาร์โมนี่",
  quest_INTRO_HARMONIE_desc: "ไปพูดคุยทำความรู้จักกับฮาร์โมนี่ที่ห้องสมุด",
  quest_INTRO_HARMONIE_obj1: "ไปที่ห้องสมุดและพูดคุยกับฮาร์โมนี่",
  quest_INTRO_HARMONIE_thanks: "...",
  quest_MEMENTO_FOR_COLLECTOR_title: "ของที่ระลึกสำหรับนักสะสม",
  quest_MEMENTO_FOR_COLLECTOR_desc: "นักสะสมของเก่ากำลังมองหา {mementoName} จาก {monsterName}",
  quest_MEMENTO_FOR_COLLECTOR_obj1: "รวบรวม {mementoName} จากการปราบ {monsterName}",
  quest_MEMENTO_FOR_COLLECTOR_obj2: "นำ {mementoName} ไปให้นักสะสมของเก่า",
  quest_MEMENTO_FOR_COLLECTOR_thanks: "ยอดเยี่ยมมาก! {mementoName} ชิ้นนี้ช่างน่าทึ่งจริงๆ",
  quest_ZALAY_BEAT_FREESTYLE_title: "บีทใหม่ของ Zalay",
  quest_ZALAY_BEAT_FREESTYLE_desc: "Zalay Beat ต้องการแรงบันดาลใจสำหรับบีทใหม่ ลองไปเล่นดนตรีในห้อง Freestyle Jam ดูสิ",
  quest_ZALAY_BEAT_FREESTYLE_obj1: "เล่นโน้ตในห้อง Freestyle Jam อย่างน้อย 20 ตัว",
  quest_ZALAY_BEAT_FREESTYLE_obj2: "กลับไปคุยกับ Zalay Beat",
  quest_ZALAY_BEAT_FREESTYLE_thanks: "สุดยอดเลยเพื่อน! เสียงที่นายเล่นเมื่อกี้มันจุดประกายไอเดียให้ฉันเลยว่ะ!",
  finalBoss_Title: "บททดสอบมหาอาจารย์โสตทิพย์",
  finalBoss_Grandmaster_Name: "มหาอาจารย์โสตทิพย์",
  finalBoss_Grandmaster_Description: "บททดสอบสุดท้ายเพื่อพิสูจน์ความเป็นสุดยอดผู้เชี่ยวชาญด้านโสตประสาท",
  finalBoss_StagePrefix: "ด่านที่",
  finalBoss_Stage1_Title: "ทดสอบความแม่นยำเรื่องขั้นคู่เสียง",
  finalBoss_Stage2_Title: "ทดสอบความเชี่ยวชาญเรื่องคอร์ด",
  finalBoss_Stage3_Title: "ทดสอบอัจฉริยภาพด้านทำนอง",
  finalBoss_LivesRemaining: "โอกาสที่เหลือ: {count}",
  finalBoss_VictoryTitle: "ยินดีด้วย!",
  finalBoss_VictoryMessage: "คุณได้พิสูจน์ความเชี่ยวชาญ และได้รับยศ '{title_GoldenEarGod}'!",
  finalBoss_DefeatTitle: "น่าเสียดาย...",
  finalBoss_DefeatMessage: "คุณเกือบจะทำสำเร็จแล้ว! พยายามอีกครั้งเพื่อเป็นเทพเจ้าหูทอง!",
  title_GoldenEarGod: "เทพเจ้าหูทอง",
  finalBoss_MainMenuButton: "บททดสอบสุดท้าย",
  ach_DEFEAT_FINAL_BOSS_name: "ผู้พิชิตมหาอาจารย์โสตทิพย์",
  ach_DEFEAT_FINAL_BOSS_desc: "เอาชนะบททดสอบสุดท้ายและได้รับยศเทพเจ้าหูทอง",
};
